import assert from 'node:assert/strict';
import test from 'node:test';
import { buildProactiveOperator } from '../src/proactive-operator.js';
import type { MuninState } from '../src/types.js';

const state:MuninState={projects:[],research:[],goals:[],relations:[],actions:[{id:'a1',title:'Preparar entrevista',priority:'P0',status:'planned',createdAt:'2026-08-20T10:00:00Z',updatedAt:'2026-08-20T10:00:00Z'}],decisions:[{id:'d1',title:'Aprovar candidatura',status:'required',createdAt:'2026-08-21T10:00:00Z'}],jobs:[{id:'j1',company:'B3',role:'Digital Assets',status:'interview',fitScore:90,matchedSignals:[],recruiter:'Isabella',nextAction:'Enviar follow-up',followUpAt:'2026-08-21T12:00:00Z',createdAt:'2026-08-01T10:00:00Z',updatedAt:'2026-08-20T10:00:00Z'}]};
test('proactive hub derives follow-ups, today, people and approval-first browser plans',()=>{const result=buildProactiveOperator({state,inbox:{messages:[{id:'m1',provider:'gmail',providerMessageId:'1',subject:'Please reply',snippet:'',receivedAt:'2026-08-21T10:00:00Z',category:'other',confidence:.8,handled:false,needsAction:true,attention:'general_action',actionReason:'Response requested'}]},manus:[],traces:[],engineering:[],now:new Date('2026-08-22T12:00:00Z')});assert.equal(result.today.length,2);assert.equal(result.waitingFor.length,2);assert.equal(result.people[0].name,'Isabella');assert.equal(result.approvals.length,2);assert.equal(result.browserPlans[0].status,'approval-required');assert.equal(result.calendar.mode,'read-only')});

test('analytics summarizes real trace and engineering evidence',()=>{const result=buildProactiveOperator({state:{...state,actions:[],decisions:[],jobs:[]},inbox:{messages:[]},manus:[],traces:[{planId:'p1',route:'direct',attempts:[{providerId:'local',ok:true}],selectedProviderId:'local',startedAt:'2026-08-22T10:00:00Z',completedAt:'2026-08-22T10:00:01Z'}],engineering:[{id:'e1',objective:'build',status:'completed',createdAt:'2026-08-22T10:00:00Z'}],now:new Date('2026-08-22T12:00:00Z')});assert.equal(result.analytics.successRate,100);assert.equal(result.analytics.engineeringCompleted,1)});
