import test from 'node:test';
import assert from 'node:assert/strict';
import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { isMuninProjectRelevant, ProjectMemoryStore } from '../src/project-memory.js';

async function fixture(){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'munin-project-memory-'));return {dir,store:new ProjectMemoryStore(path.join(dir,'project-memory.json'))}}

test('project relevance excludes unrelated chat by default',()=>{assert.equal(isMuninProjectRelevant('Munin should use local-first memory'),true);assert.equal(isMuninProjectRelevant('MuninHQ/munin-foundation issue 127'),true);assert.equal(isMuninProjectRelevant('qual a melhor hamburgueria perto de mim?'),false)});

test('captures, deduplicates and supersedes project decisions',async()=>{const {store}=await fixture();const first=await store.capture({kind:'decision',title:'Memory substrate',content:'Keep Munin-native memory as baseline.',project:'munin',source:'session:a',observedAt:'2026-08-15T18:00:00Z',confidence:'confirmed',tags:['memory'],relatedIssues:['#118']});assert.equal(first.created,true);const duplicate=await store.capture({kind:'decision',title:'Memory substrate',content:'Keep Munin-native memory as baseline.',project:'munin',source:'session:a',observedAt:'2026-08-15T18:00:00Z',confidence:'confirmed',tags:['memory'],relatedIssues:['#118']});assert.equal(duplicate.created,false);const second=await store.capture({kind:'decision',title:'Memory substrate',content:'Benchmark candidates before replacing Munin-native memory.',project:'munin',source:'session:b',observedAt:'2026-08-15T19:00:00Z',confidence:'confirmed',tags:['memory','benchmark'],relatedIssues:['#118']});assert.equal(second.superseded,1);assert.equal(second.record.supersedes.length,1);const current=await store.currentState();assert.equal(current.length,1);assert.match(current[0].content,/Benchmark candidates/);const history=await store.search('Memory substrate',10,true);assert.equal(history.length,2);assert.equal(history.some(x=>x.status==='superseded'),true)});

test('reconstructs and exports current project state with provenance',async()=>{const {store}=await fixture();await store.capture({kind:'architecture',title:'Local-first runtime',content:'Private memory remains under data/runtime and outside Git.',project:'munin',source:'github:#127',observedAt:'2026-08-15T19:00:00Z',confidence:'confirmed',tags:['privacy','architecture'],relatedIssues:['#127']});await store.capture({kind:'backlog',title:'Agent Skills',content:'Evaluate progressive disclosure via SKILL.md.',project:'munin',source:'github:#119',observedAt:'2026-08-15T19:01:00Z',confidence:'confirmed',tags:['skills'],relatedIssues:['#119']});const state=await store.reconstruct('Munin');assert.equal(state.records.length,2);assert.equal(Array.isArray(state.byKind.architecture),true);const markdown=await store.exportMarkdown();assert.match(markdown,/Local-first runtime/);assert.match(markdown,/github:#127/);const stats=await store.stats();assert.equal(stats.current,2)});
