type AssistantResponse={kind:string;message:string;data?:unknown;mutated?:boolean};
const css=`.munin-ai-launch{position:fixed;right:28px;bottom:26px;z-index:40;width:52px;height:52px;border-radius:50%;border:1px solid #2d83b8;background:#0a2435;color:#86d6ff;font-size:20px;box-shadow:0 12px 35px #0009,0 0 25px #1175ad44;cursor:pointer}.munin-ai-dock{position:fixed;right:24px;bottom:90px;width:390px;max-height:620px;z-index:40;border:1px solid #28506b;border-radius:15px;background:#07131f;box-shadow:0 30px 80px #000c;display:none;overflow:hidden}.munin-ai-dock.open{display:flex;flex-direction:column}.munin-ai-head{display:flex;justify-content:space-between;align-items:center;padding:17px 18px;border-bottom:1px solid #173044}.munin-ai-head strong{letter-spacing:.16em;font-size:12px}.munin-ai-head small{display:block;color:#5d829a;font-size:9px;margin-top:3px}.munin-ai-close{border:0;background:transparent;color:#7895a8;font-size:22px;cursor:pointer}.munin-ai-log{padding:14px;overflow:auto;min-height:210px;max-height:430px}.munin-ai-msg{padding:11px 12px;border-radius:10px;margin:8px 0;font-size:12px;line-height:1.5;white-space:pre-wrap}.munin-ai-msg.user{background:#10283a;margin-left:34px}.munin-ai-msg.assistant{background:#0a1b28;border:1px solid #19394f;margin-right:20px;color:#bdd5e4}.munin-ai-form{display:flex;gap:8px;padding:12px;border-top:1px solid #173044}.munin-ai-form input{flex:1;border:1px solid #24445b;border-radius:9px;background:#050e17;color:#eef6ff;padding:11px;outline:none}.munin-ai-form button{border:1px solid #2d83b8;border-radius:9px;background:#126a9f;color:white;padding:0 14px;cursor:pointer}.munin-ai-hints{padding:0 14px 12px;color:#57788e;font-size:9px}`;
const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
const launch=document.createElement('button');launch.className='munin-ai-launch';launch.title='Munin Assistant';launch.textContent='ᛗ';
const dock=document.createElement('section');dock.className='munin-ai-dock';dock.innerHTML=`<div class="munin-ai-head"><div><strong>MUNIN ASSISTANT</strong><small>EXECUTIVE COMMAND DOCK</small></div><button class="munin-ai-close">×</button></div><div class="munin-ai-log"><div class="munin-ai-msg assistant">Pronto. Posso gerar SITREP, priorizar seu dia, criar ações/projetos/vagas/pesquisas e buscar contexto.</div></div><div class="munin-ai-hints">Ex.: “prioridades de hoje” · “criar ação: follow-up B3 P0” · “buscar Drex”</div><form class="munin-ai-form"><input placeholder="O que você quer fazer?" autocomplete="off"/><button>Enviar</button></form>`;
document.body.append(dock,launch);
const log=dock.querySelector('.munin-ai-log') as HTMLDivElement;const form=dock.querySelector('form') as HTMLFormElement;const input=dock.querySelector('input') as HTMLInputElement;
function msg(text:string,role:'user'|'assistant'){const el=document.createElement('div');el.className=`munin-ai-msg ${role}`;el.textContent=text;log.appendChild(el);log.scrollTop=log.scrollHeight;}
launch.onclick=()=>{dock.classList.toggle('open');if(dock.classList.contains('open'))setTimeout(()=>input.focus(),0)};(dock.querySelector('.munin-ai-close') as HTMLButtonElement).onclick=()=>dock.classList.remove('open');
form.onsubmit=async e=>{e.preventDefault();const command=input.value.trim();if(!command)return;msg(command,'user');input.value='';input.disabled=true;try{const response=await fetch('/api/assistant',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({command})});const data=await response.json() as AssistantResponse;if(!response.ok)throw new Error((data as any).error||'Falha');let text=data.message;if(data.kind==='context'&&Array.isArray(data.data)){text+='\n'+data.data.slice(0,6).map((x:any)=>`• ${x.label??x.name??x.title??x.id}`).join('\n')}msg(text,'assistant');if(data.mutated)window.dispatchEvent(new Event('munin:refresh'));}catch(error){msg(error instanceof Error?error.message:String(error),'assistant')}finally{input.disabled=false;input.focus()}};
window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='j'){e.preventDefault();dock.classList.add('open');input.focus();}});
