import './career-validation.css';

type Validation={total:number;correct:number;needsCorrection:number;accuracy:number;meetsTarget:boolean;target:number};
type Snapshot={focus?:{id:string};validation:Validation};
const token=()=>localStorage.getItem('munin-mobile-token')??'';
async function request<T>(path:string,init:RequestInit={}):Promise<T>{const headers=new Headers(init.headers);headers.set('Authorization',`Bearer ${token()}`);if(init.body)headers.set('Content-Type','application/json');const response=await fetch(path,{...init,headers});const payload=await response.json().catch(()=>({error:`HTTP ${response.status}`}));if(!response.ok)throw new Error(payload.error??`HTTP ${response.status}`);return payload as T}
function metricText(v:Validation){if(!v.total)return'Validação ainda sem amostra';return`${Math.round(v.accuracy*100)}% de continuidade correta · ${v.total} validações`}
async function mount(){const realm=document.querySelector<HTMLElement>('[data-career-realm]');const focus=realm?.querySelector<HTMLElement>('.career-focus');if(!realm||!focus||realm.querySelector('[data-continuity-validation]'))return;try{const snapshot=await request<Snapshot>('/api/mobile/career');const box=document.createElement('div');box.className='career-validation';box.dataset.continuityValidation='true';box.innerHTML=`<div class="career-validation-metric"><span>HIPÓTESE #4</span><strong>${metricText(snapshot.validation)}</strong></div>${snapshot.focus?'<div class="career-validation-actions"><small>O Munin reconstruiu este contexto corretamente?</small><div><button data-verdict="correct">✓ Sim</button><button data-verdict="needs_correction" class="needs-correction">Corrigir</button></div></div>':''}`;focus.after(box);box.querySelectorAll<HTMLButtonElement>('[data-verdict]').forEach(button=>button.addEventListener('click',async()=>{const verdict=button.dataset.verdict;box.classList.add('busy');try{const result=await request<{validation:Validation}>('/api/mobile/career/feedback',{method:'POST',body:JSON.stringify({jobId:snapshot.focus?.id,verdict})});box.innerHTML=`<div class="career-validation-metric"><span>REGISTRADO</span><strong>${metricText(result.validation)}</strong></div>`}catch(e){box.classList.remove('busy');button.textContent=e instanceof Error?e.message:'Falha ao registrar'}}))}catch{/* Career Realm itself owns fetch/retry errors. */}}
let scheduled=false;function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;void mount()})}new MutationObserver(schedule).observe(document.documentElement,{subtree:true,childList:true});document.addEventListener('click',schedule,true);schedule();
