import './career-realm.css';

type CareerSignal={id:string;at:string;category:string;subject:string;from?:string;confidence:number};
type CareerProcess={id:string;company:string;role:string;status:string;fitScore:number;nextAction:string;followUpAt?:string;lastSignalAt?:string;signalCount:number;needsAttention:boolean;automation:'auto'|'review'|'none';provenance:CareerSignal[]};
type CareerSnapshot={generatedAt:string;counts:{active:number;interviews:number;followUps:number;attention:number;stale:number};focus?:CareerProcess;active:CareerProcess[]};

const token=()=>localStorage.getItem('munin-mobile-token')??'';
async function api<T>(path:string):Promise<T>{const response=await fetch(path,{headers:{Authorization:`Bearer ${token()}`}});const payload=await response.json().catch(()=>({error:`HTTP ${response.status}`}));if(!response.ok)throw new Error(payload.error??`HTTP ${response.status}`);return payload as T}
function escapeHtml(value:string){return value.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]??c))}
function fmt(value?:string){if(!value)return'—';const d=new Date(value);return Number.isNaN(d.getTime())?'—':d.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})}
function statusLabel(value:string){return({discovered:'Descoberta',investigating:'Investigando',applied:'Aplicada',interview:'Entrevista',offer:'Oferta',rejected:'Encerrada',closed:'Fechada'} as Record<string,string>)[value]??value}

function render(host:HTMLElement,s:CareerSnapshot){
 const focus=s.focus;host.innerHTML=`<div class="career-realm-head"><div><span class="eyebrow">CAREER CONTINUITY</span><h3>Transição profissional</h3><p>Estado persistente, sinais recentes e próximo movimento sem reconstruir contexto.</p></div><button data-career-refresh class="career-refresh" aria-label="Atualizar carreira">↻</button></div><div class="career-metrics"><article><strong>${s.counts.active}</strong><small>ativos</small></article><article><strong>${s.counts.interviews}</strong><small>entrevistas</small></article><article><strong>${s.counts.followUps}</strong><small>follow-ups</small></article><article><strong>${s.counts.attention}</strong><small>revisar</small></article></div>${focus?`<article class="career-focus"><span>PRÓXIMO MOVIMENTO</span><strong>${escapeHtml(focus.company)} · ${escapeHtml(focus.role)}</strong><p>${escapeHtml(focus.nextAction)}</p><div><b>${escapeHtml(statusLabel(focus.status))}</b><small>${focus.fitScore}% fit · ${focus.signalCount} sinais</small></div></article>`:'<div class="career-empty">Nenhum processo ativo.</div>'}<div class="career-process-list">${s.active.slice(0,8).map(p=>`<article class="career-process ${p.needsAttention?'attention':''}"><div class="career-process-top"><div><strong>${escapeHtml(p.company)}</strong><small>${escapeHtml(p.role)}</small></div><span>${escapeHtml(statusLabel(p.status))}</span></div><p>${escapeHtml(p.nextAction)}</p><div class="career-process-meta"><span>${p.fitScore}% fit</span><span>${p.signalCount} sinais</span><span>${p.followUpAt?`follow-up ${fmt(p.followUpAt)}`:`último sinal ${fmt(p.lastSignalAt)}`}</span>${p.automation==='review'?'<b>revisão</b>':''}</div></article>`).join('')}</div><small class="career-updated">Atualizado ${new Date(s.generatedAt).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</small>`;
 host.querySelector('[data-career-refresh]')?.addEventListener('click',()=>void load(host));
}
async function load(host:HTMLElement){host.classList.add('loading');try{render(host,await api<CareerSnapshot>('/api/mobile/career'))}catch(e){host.innerHTML=`<div class="career-error"><strong>Career Continuity indisponível</strong><small>${escapeHtml(e instanceof Error?e.message:String(e))}</small><button data-career-refresh>Tentar novamente</button></div>`;host.querySelector('[data-career-refresh]')?.addEventListener('click',()=>void load(host))}finally{host.classList.remove('loading')}}
function mount(){const realms=[...document.querySelectorAll<HTMLElement>('.realm-page')].find(p=>p.querySelector('h2')?.textContent?.trim()==='Realms');if(!realms||realms.querySelector('[data-career-realm]'))return;const host=document.createElement('section');host.className='career-realm';host.dataset.careerRealm='true';host.innerHTML='<div class="career-loading">Reconstruindo fio de carreira…</div>';realms.prepend(host);void load(host)}
let scheduled=false;function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;mount()})}new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});document.addEventListener('click',schedule,true);window.addEventListener('load',schedule);schedule();
