import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { ContextStore } from './store.js';
import { MuninService } from './service.js';
import { buildKnowledgeGraph, buildTimeline, generateDailyBrief, generateInsights, resolveContext } from './intelligence.js';
import type { JobStatus, Priority, Status } from './types.js';
import { CareerInboxStore } from './career-inbox.js';
import { syncCareerInbox } from './email-providers.js';
import { beginOAuth, completeOAuth, connectionStatus, disconnect, type OAuthProvider } from './oauth.js';
import { captureCareerMessage, type CaptureFormat } from './career-capture.js';
import { CareerWatchFolder } from './watch-folder.js';
import { executeAssistantCommand } from './assistant.js';
import { clearAssistantMemory, loadAssistantMemory } from './assistant-memory.js';
import { deleteLlmSettings, loadLlmSettings, publicLlmSettings, saveLlmSettings, type LlmProviderType } from './llm-settings.js';
import { llmProviderStatus, testLlmProvider } from './llm-provider.js';
import { addLinkedInPost, createPostDraft, loadLinkedInContent, suggestLinkedInTopics, updateVisualProfile, type LinkedInPostStatus } from './linkedin-content.js';
import { deleteImageSettings, loadImageSettings, publicImageSettings, saveImageSettings } from './image-settings.js';
import { generateLinkedInImage, getGeneratedImage, imageProviderStatus, testImageProvider } from './image-provider.js';
import { bytes, json, readJsonBody, redirect, requireText as text } from './http.js';
import { apiPort, webBaseUrl } from './config.js';
import { trustedSourceRadar } from './trusted-source-radar.js';
import { buildActionInbox } from './action-inbox.js';
import { connectorRegistry } from './connector-registry.js';
import { ManusTaskStore, manusBridgeStatus, refreshManusTasks, submitManusTask, type ManusTaskKind } from './manus-operational-bridge.js';
import { buildProactiveOperator } from './proactive-operator.js';
import { recentOrchestrationTraces } from './orchestration-api.js';
import { readFile } from 'node:fs/promises';
import { runtimePath } from './config.js';
import type { EngineeringJob } from './engineering-jobs.js';
import { createContentVideoCapability, contentVideoPolicy, type ContentVideoInput } from './content-video-capability.js';
import { firecrawlHealth, scrapeWithFirecrawl } from './firecrawl-context.js';
import { localVideoPolicy } from './local-video-capability.js';
const store=new ContextStore(); const service=new MuninService(store); const inbox=new CareerInboxStore(); const watchFolder=new CareerWatchFolder();
const manusTasks=new ManusTaskStore();
const body=(request:IncomingMessage)=>readJsonBody(request,5_000_000);
export async function handleApi(request:IncomingMessage,response:ServerResponse):Promise<void>{if(request.method==='OPTIONS')return json(request,response,204,{});const url=new URL(request.url??'/','http://localhost');try{
if(request.method==='GET'&&url.pathname==='/api/health')return json(request,response,200,{status:'ok',service:'munin-workspace'});
if(request.method==='GET'&&url.pathname==='/api/content-studio/status')return json(request,response,200,{generatedAt:new Date().toISOString(),contentVideo:contentVideoPolicy(),localVideo:localVideoPolicy(),documents:{preferredEngine:process.env.MUNIN_DOCUMENT_ENGINE||'docling',mineruRunnerConfigured:Boolean(process.env.MUNIN_MINERU_RUNNER)},webContext:firecrawlHealth(),publication:{automatic:false,humanApprovalRequired:true}});
if(request.method==='POST'&&url.pathname==='/api/content-studio/video'){const input=await body(request);const action=input.action==='generate'?'generate':'plan';const capability=createContentVideoCapability();const capabilityInput={action,topic:text(input.topic,'topic'),script:typeof input.script==='string'?input.script:undefined,language:typeof input.language==='string'?input.language:undefined,aspectRatio:input.aspectRatio==='16:9'||input.aspectRatio==='1:1'?input.aspectRatio:'9:16'} as ContentVideoInput;return json(request,response,action==='generate'?201:200,await capability.execute(capabilityInput,{capability:'media.content-video',executionId:`content-studio-${Date.now()}`,startedAt:new Date().toISOString(),input:capabilityInput,metadata:{source:'content-studio'}}));}
if(request.method==='POST'&&url.pathname==='/api/content-studio/scrape'){const input=await body(request);return json(request,response,200,await scrapeWithFirecrawl(text(input.url,'url')));}
if(request.method==='GET'&&url.pathname==='/api/radar'){const snapshot=await trustedSourceRadar(url.searchParams.get('refresh')==='1');return json(request,response,200,snapshot);}
if(request.method==='GET'&&url.pathname==='/api/action-inbox'){const [state,email,radar,manus]=await Promise.all([store.load(),inbox.load(),trustedSourceRadar(false),manusTasks.list()]);return json(request,response,200,buildActionInbox(state,email,radar,new Date(),manus));}
if(request.method==='GET'&&url.pathname==='/api/connectors'){const [radar,connections,manus]=await Promise.all([trustedSourceRadar(false),connectionStatus(),manusBridgeStatus(manusTasks)]);return json(request,response,200,{generatedAt:new Date().toISOString(),items:[...connectorRegistry(radar,connections),{id:'manus',name:'Manus Operational Bridge',category:'research',cost:'free',auth:'oauth',enabled:manus.enabled,health:manus.enabled?'healthy':'not-connected',detail:manus.enabled?`${manus.profile} · ${manus.declaredCreditsToday}/${manus.dailyCreditBudget} créditos reservados hoje`:manus.reason}]});}
if(request.method==='GET'&&url.pathname==='/api/manus/status')return json(request,response,200,await manusBridgeStatus(manusTasks));
if(request.method==='GET'&&url.pathname==='/api/manus/tasks')return json(request,response,200,{items:await manusTasks.list()});
if(request.method==='GET'&&url.pathname==='/api/proactive-operator'){let engineering:EngineeringJob[]=[];try{engineering=JSON.parse(await readFile(runtimePath('engineering-jobs.json'),'utf8')) as EngineeringJob[]}catch{}const [state,email,manus]=await Promise.all([store.load(),inbox.load(),manusTasks.list()]);return json(request,response,200,buildProactiveOperator({state,inbox:email,manus,traces:recentOrchestrationTraces(),engineering}));}
if(request.method==='POST'&&url.pathname==='/api/manus/tasks'){const input=await body(request);return json(request,response,201,await submitManusTask({kind:text(input.kind,'kind') as ManusTaskKind,title:text(input.title,'title'),prompt:text(input.prompt,'prompt'),declaredCreditBudget:typeof input.declaredCreditBudget==='number'?input.declaredCreditBudget:undefined},manusTasks));}
if(request.method==='POST'&&url.pathname==='/api/manus/refresh')return json(request,response,200,{items:await refreshManusTasks(manusTasks)});
if(request.method==='GET'&&url.pathname==='/api/workspace'){const state=await store.load();const events=await store.events();const careerQueue=await service.careerQueue();return json(request,response,200,{state,events:events.slice(-20).reverse(),careerQueue,intelligence:{dailyBrief:generateDailyBrief(state),timeline:buildTimeline(state,events,30),graph:buildKnowledgeGraph(state),insights:generateInsights(state).slice(0,20)}});}
if(request.method==='POST'&&url.pathname==='/api/assistant'){const input=await body(request);return json(request,response,200,await executeAssistantCommand(text(input.command,'command')));}
if(request.method==='GET'&&url.pathname==='/api/assistant/history')return json(request,response,200,await loadAssistantMemory());
if(request.method==='DELETE'&&url.pathname==='/api/assistant/history')return json(request,response,200,await clearAssistantMemory());
if(request.method==='GET'&&url.pathname==='/api/settings/llm')return json(request,response,200,{settings:publicLlmSettings(await loadLlmSettings()),status:await llmProviderStatus()});
if(request.method==='PUT'&&url.pathname==='/api/settings/llm'){const input=await body(request);const provider=input.provider==='anthropic'?'anthropic':input.provider==='openai-compatible'?'openai-compatible':undefined;const settings=await saveLlmSettings({enabled:typeof input.enabled==='boolean'?input.enabled:undefined,provider:provider as LlmProviderType|undefined,baseUrl:typeof input.baseUrl==='string'?input.baseUrl:undefined,apiKey:typeof input.apiKey==='string'?input.apiKey:undefined,model:typeof input.model==='string'?input.model:undefined});return json(request,response,200,{settings,status:await llmProviderStatus()});}
if(request.method==='DELETE'&&url.pathname==='/api/settings/llm'){const settings=await deleteLlmSettings();return json(request,response,200,{settings,status:await llmProviderStatus()});}
if(request.method==='POST'&&url.pathname==='/api/settings/llm/test')return json(request,response,200,await testLlmProvider());
if(request.method==='GET'&&url.pathname==='/api/settings/image')return json(request,response,200,{settings:publicImageSettings(await loadImageSettings()),status:await imageProviderStatus()});
if(request.method==='PUT'&&url.pathname==='/api/settings/image'){const input=await body(request);const size=input.size==='1024x1024'?'1024x1024':input.size==='1024x1536'?'1024x1536':undefined;const quality=input.quality==='low'||input.quality==='medium'||input.quality==='high'?input.quality:undefined;const settings=await saveImageSettings({enabled:typeof input.enabled==='boolean'?input.enabled:undefined,baseUrl:typeof input.baseUrl==='string'?input.baseUrl:undefined,apiKey:typeof input.apiKey==='string'?input.apiKey:undefined,model:typeof input.model==='string'?input.model:undefined,size,quality});return json(request,response,200,{settings,status:await imageProviderStatus()});}
if(request.method==='DELETE'&&url.pathname==='/api/settings/image')return json(request,response,200,{settings:await deleteImageSettings(),status:await imageProviderStatus()});
if(request.method==='POST'&&url.pathname==='/api/settings/image/test')return json(request,response,200,await testImageProvider());
if(request.method==='GET'&&url.pathname==='/api/linkedin-content'){const content=await loadLinkedInContent();return json(request,response,200,{...content,suggestions:await suggestLinkedInTopics(),imageProvider:await imageProviderStatus()});}
if(request.method==='POST'&&url.pathname==='/api/linkedin-content/posts'){const input=await body(request);const status=(input.status==='draft'||input.status==='idea'||input.status==='published'?input.status:'published') as LinkedInPostStatus;return json(request,response,201,await addLinkedInPost({title:text(input.title,'title'),body:text(input.body,'body'),publishedAt:typeof input.publishedAt==='string'&&input.publishedAt?input.publishedAt:undefined,status,themes:Array.isArray(input.themes)?input.themes.filter(x=>typeof x==='string') as string[]:undefined,visualConcept:typeof input.visualConcept==='string'?input.visualConcept:undefined,imagePrompt:typeof input.imagePrompt==='string'?input.imagePrompt:undefined,sourceUrl:typeof input.sourceUrl==='string'?input.sourceUrl:undefined,notes:typeof input.notes==='string'?input.notes:undefined}));}
if(request.method==='POST'&&url.pathname==='/api/linkedin-content/drafts'){const input=await body(request);return json(request,response,201,await createPostDraft({title:text(input.title,'title'),angle:text(input.angle,'angle'),themes:Array.isArray(input.themes)?input.themes.filter(x=>typeof x==='string') as string[]:undefined}));}
if(request.method==='POST'&&url.pathname==='/api/linkedin-content/images'){const input=await body(request);const asset=await generateLinkedInImage(text(input.prompt,'prompt'),typeof input.postId==='string'?input.postId:undefined);return json(request,response,201,{...asset,url:`/api/linkedin-content/images/${asset.id}`});}
const image=url.pathname.match(/^\/api\/linkedin-content\/images\/([^/]+)$/);if(request.method==='GET'&&image){const generated=await getGeneratedImage(image[1]);return bytes(request,response,generated.bytes,{'content-type':generated.asset.mimeType,'cache-control':'private, max-age=31536000, immutable'});}
if(request.method==='PUT'&&url.pathname==='/api/linkedin-content/visual-profile'){const input=await body(request);return json(request,response,200,await updateVisualProfile({name:typeof input.name==='string'?input.name:undefined,background:typeof input.background==='string'?input.background:undefined,composition:typeof input.composition==='string'?input.composition:undefined,accent:typeof input.accent==='string'?input.accent:undefined,style:typeof input.style==='string'?input.style:undefined,avoid:Array.isArray(input.avoid)?input.avoid.filter(x=>typeof x==='string') as string[]:undefined,logoTreatment:typeof input.logoTreatment==='string'?input.logoTreatment:undefined}));}
if(request.method==='GET'&&url.pathname==='/api/sitrep')return json(request,response,200,{report:await service.sitrep()});
if(request.method==='GET'&&url.pathname==='/api/intelligence/timeline'){const state=await store.load();return json(request,response,200,{items:buildTimeline(state,await store.events(),Number(url.searchParams.get('limit')??100))});}
if(request.method==='GET'&&url.pathname==='/api/intelligence/graph')return json(request,response,200,buildKnowledgeGraph(await store.load()));
if(request.method==='GET'&&url.pathname==='/api/intelligence/daily-brief')return json(request,response,200,generateDailyBrief(await store.load()));
if(request.method==='GET'&&url.pathname==='/api/intelligence/insights')return json(request,response,200,{items:generateInsights(await store.load())});
if(request.method==='GET'&&url.pathname==='/api/intelligence/context')return json(request,response,200,{query:url.searchParams.get('q')??'',matches:resolveContext(await store.load(),url.searchParams.get('q')??'')});
if(request.method==='GET'&&url.pathname==='/api/career-inbox'){const state=await inbox.load();return json(request,response,200,{...state,connections:await connectionStatus(),watchFolder:await watchFolder.status()});}
if(request.method==='POST'&&url.pathname==='/api/career-inbox/sync')return json(request,response,200,await syncCareerInbox());
if(request.method==='POST'&&url.pathname==='/api/career-inbox/capture'){const input=await body(request);const format=text(input.format,'format') as CaptureFormat;if(!['eml','text','txt','msg'].includes(format))throw new Error('Unsupported capture format');return json(request,response,201,await captureCareerMessage({format,filename:typeof input.filename==='string'?input.filename:undefined,content:text(input.content,'content')}));}
if(request.method==='POST'&&url.pathname==='/api/career-inbox/capture-bulk'){const input=await body(request);if(!Array.isArray(input.items))throw new Error('items array is required');if(input.items.length>50)throw new Error('Maximum 50 messages per batch');let added=0,duplicates=0;const errors:{filename?:string;error:string}[]=[];for(const raw of input.items){try{if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new Error('Invalid item');const item=raw as Record<string,unknown>;const format=text(item.format,'format') as CaptureFormat;if(!['eml','text','txt','msg'].includes(format))throw new Error('Unsupported capture format');const result=await captureCareerMessage({format,filename:typeof item.filename==='string'?item.filename:undefined,content:text(item.content,'content')});if(result.added)added++;else duplicates++;}catch(error){const item=raw&&typeof raw==='object'&&!Array.isArray(raw)?raw as Record<string,unknown>:{};errors.push({filename:typeof item.filename==='string'?item.filename:undefined,error:error instanceof Error?error.message:String(error)});}}return json(request,response,201,{processed:input.items.length,added,duplicates,errors});}
if(request.method==='GET'&&url.pathname==='/api/career-inbox/watch-folder')return json(request,response,200,await watchFolder.status());
if(request.method==='POST'&&url.pathname==='/api/career-inbox/watch-folder'){const input=await body(request);const enabled=input.enabled===true;const folder=typeof input.folder==='string'&&input.folder.trim()?input.folder.trim():undefined;return json(request,response,200,await watchFolder.configure(folder,enabled));}
if(request.method==='POST'&&url.pathname==='/api/career-inbox/watch-folder/scan')return json(request,response,200,await watchFolder.scan());
if(request.method==='GET'&&url.pathname==='/api/oauth/status')return json(request,response,200,{connections:await connectionStatus()});
const connect=url.pathname.match(/^\/api\/oauth\/(gmail|outlook)\/connect$/);if(request.method==='GET'&&connect)return redirect(response,await beginOAuth(connect[1] as OAuthProvider));
const remove=url.pathname.match(/^\/api\/oauth\/(gmail|outlook)$/);if(request.method==='DELETE'&&remove){await disconnect(remove[1] as OAuthProvider);return json(request,response,200,{ok:true});}
if(request.method==='GET'&&url.pathname==='/api/oauth/callback'){const code=text(url.searchParams.get('code'),'code');const stateId=text(url.searchParams.get('state'),'state');const provider=await completeOAuth(code,stateId);return redirect(response,`${webBaseUrl()}/career-inbox.html?connected=${provider}`);}
const apply=url.pathname.match(/^\/api\/career-inbox\/([^/]+)\/apply$/);if(request.method==='POST'&&apply){const state=await inbox.load();const message=state.messages.find(item=>item.id===apply[1]);if(!message)throw new Error('Email not found');if(message.linkedJobId&&message.suggestedStatus)await service.updateJob(message.linkedJobId,message.suggestedStatus,message.suggestedAction);message.handled=true;await inbox.save(state);return json(request,response,200,{message});}
const createFromEmail=url.pathname.match(/^\/api\/career-inbox\/([^/]+)\/create-job$/);if(request.method==='POST'&&createFromEmail){const state=await inbox.load();const message=state.messages.find(item=>item.id===createFromEmail[1]);if(!message)throw new Error('Email not found');if(message.linkedJobId)throw new Error('Email is already linked to an opportunity');const input=await body(request);const company=typeof input.company==='string'&&input.company.trim()?input.company.trim():message.detectedCompany?.trim();const role=typeof input.role==='string'&&input.role.trim()?input.role.trim():message.detectedRole?.trim()||message.subject.trim();if(!company)throw new Error('Company is required to create an opportunity');const job=await service.addJob(company,role,`Created from career email: ${message.subject}\n\n${message.snippet}`);message.linkedJobId=job.id;message.detectedCompany=company;message.detectedRole=role;if(message.suggestedStatus)await service.updateJob(job.id,message.suggestedStatus,message.suggestedAction);message.handled=true;await inbox.save(state);return json(request,response,201,{message,job});}
const ignore=url.pathname.match(/^\/api\/career-inbox\/([^/]+)\/ignore$/);if(request.method==='POST'&&ignore){const state=await inbox.load();const message=state.messages.find(item=>item.id===ignore[1]);if(!message)throw new Error('Email not found');message.handled=true;await inbox.save(state);return json(request,response,200,{message});}
if(request.method==='POST'&&url.pathname==='/api/projects'){const input=await body(request);return json(request,response,201,await service.addProject(text(input.name,'name'),(input.priority as Priority|undefined)??'P1'));}
if(request.method==='POST'&&url.pathname==='/api/actions'){const input=await body(request);return json(request,response,201,await service.addAction(text(input.title,'title'),(input.priority as Priority|undefined)??'P1',typeof input.projectId==='string'&&input.projectId?input.projectId:undefined));}
if(request.method==='POST'&&url.pathname==='/api/jobs'){const input=await body(request);return json(request,response,201,await service.addJob(text(input.company,'company'),text(input.role,'role'),typeof input.description==='string'?input.description:''));}
if(request.method==='POST'&&url.pathname==='/api/research'){const input=await body(request);return json(request,response,201,await service.addResearch(text(input.question,'question'),typeof input.projectId==='string'&&input.projectId?input.projectId:undefined));}
const project=url.pathname.match(/^\/api\/projects\/([^/]+)$/);if(request.method==='PATCH'&&project){const input=await body(request);return json(request,response,200,await service.updateProject(project[1],text(input.status,'status') as Status,typeof input.nextAction==='string'?input.nextAction:undefined));}
const job=url.pathname.match(/^\/api\/jobs\/([^/]+)$/);if(request.method==='PATCH'&&job){const input=await body(request);return json(request,response,200,await service.updateJob(job[1],text(input.status,'status') as JobStatus,typeof input.nextAction==='string'?input.nextAction:undefined));}
const touch=url.pathname.match(/^\/api\/jobs\/([^/]+)\/touch$/);if(request.method==='POST'&&touch){const input=await body(request);return json(request,response,200,await service.touchJob(touch[1],typeof input.note==='string'?input.note:undefined));}
const action=url.pathname.match(/^\/api\/actions\/([^/]+)\/complete$/);if(request.method==='POST'&&action){const input=await body(request);return json(request,response,200,await service.execute(action[1],typeof input.outcome==='string'&&input.outcome.trim()?input.outcome.trim():'Completed'));}
const evidence=url.pathname.match(/^\/api\/research\/([^/]+)\/evidence$/);if(request.method==='POST'&&evidence){const input=await body(request);return json(request,response,201,await service.addEvidence(evidence[1],text(input.title,'title'),text(input.url,'url'),(input.sourceType as 'primary'|'secondary'|undefined)??'secondary',typeof input.note==='string'?input.note:undefined));}
const synthesis=url.pathname.match(/^\/api\/research\/([^/]+)\/synthesize$/);if(request.method==='POST'&&synthesis){const input=await body(request);return json(request,response,201,await service.synthesizeResearch(synthesis[1],text(input.summary,'summary')));}
return json(request,response,404,{error:'Not found'});}catch(error){return json(request,response,400,{error:error instanceof Error?error.message:String(error)});}}
/** Start background jobs owned by the core API (career watch folder). */
export function startBackgroundJobs(){watchFolder.start();}
export function createApiServer(){startBackgroundJobs();return createServer((request,response)=>void handleApi(request,response));}
if(process.argv[1]?.endsWith('api.js')){const port=apiPort();createApiServer().listen(port,'127.0.0.1',()=>console.log(`Munin API running at http://127.0.0.1:${port}`));}
