import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { ContextStore } from './store.js';
import { MuninService } from './service.js';
import { buildKnowledgeGraph, buildTimeline, generateDailyBrief, generateInsights, resolveContext } from './intelligence.js';
import type { JobStatus, Priority, Status } from './types.js';
import { CareerInboxStore } from './career-inbox.js';
import { syncCareerInbox } from './email-providers.js';
import { beginOAuth, completeOAuth, connectionStatus, disconnect, type OAuthProvider } from './oauth.js';
import { captureCareerMessage, type CaptureFormat } from './career-capture.js';
import { CareerWatchFolder } from './watch-folder.js';
import { executeAssistantCommand } from './assistant.js';
import { clearAssistantMemory, loadAssistantMemory } from './assistant-memory.js';
import { deleteLlmSettings, loadLlmSettings, publicLlmSettings, saveLlmSettings, type LlmProviderType } from './llm-settings.js';
import { llmProviderStatus, testLlmProvider } from './llm-provider.js';
const store=new ContextStore(); const service=new MuninService(store); const inbox=new CareerInboxStore(); const watchFolder=new CareerWatchFolder();
function json(response:ServerResponse,status:number,body:unknown){response.writeHead(status,{'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','access-control-allow-headers':'content-type','access-control-allow-methods':'GET,POST,PATCH,PUT,DELETE,OPTIONS'});response.end(JSON.stringify(body));}
function redirect(response:ServerResponse,url:string){response.writeHead(302,{location:url});response.end();}
async function body(request:IncomingMessage):Promise<Record<string,unknown>>{const chunks:Buffer[]=[];let size=0;for await(const chunk of request){const value=Buffer.from(chunk);size+=value.length;if(size>5_000_000)throw new Error('Payload too large');chunks.push(value);}if(!chunks.length)return{};const parsed=JSON.parse(Buffer.concat(chunks).toString('utf8')) as unknown;if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new Error('JSON object body required');return parsed as Record<string,unknown>;}
function text(value:unknown,field:string){if(typeof value!=='string'||!value.trim())throw new Error(`${field} is required`);return value.trim();}
export async function handleApi(request:IncomingMessage,response:ServerResponse):Promise<void>{if(request.method==='OPTIONS')return json(response,204,{});const url=new URL(request.url??'/','http://localhost');try{
if(request.method==='GET'&&url.pathname==='/api/health')return json(response,200,{status:'ok',service:'munin-workspace'});
if(request.method==='GET'&&url.pathname==='/api/workspace'){const state=await store.load();const events=await store.events();const careerQueue=await service.careerQueue();return json(response,200,{state,events:events.slice(-20).reverse(),careerQueue,intelligence:{dailyBrief:generateDailyBrief(state),timeline:buildTimeline(state,events,30),graph:buildKnowledgeGraph(state),insights:generateInsights(state).slice(0,20)}});}
if(request.method==='POST'&&url.pathname==='/api/assistant'){const input=await body(request);return json(response,200,await executeAssistantCommand(text(input.command,'command')));}
if(request.method==='GET'&&url.pathname==='/api/assistant/history')return json(response,200,await loadAssistantMemory());
if(request.method==='DELETE'&&url.pathname==='/api/assistant/history')return json(response,200,await clearAssistantMemory());
if(request.method==='GET'&&url.pathname==='/api/settings/llm')return json(response,200,{settings:publicLlmSettings(await loadLlmSettings()),status:await llmProviderStatus()});
if(request.method==='PUT'&&url.pathname==='/api/settings/llm'){const input=await body(request);const provider=input.provider==='anthropic'?'anthropic':input.provider==='openai-compatible'?'openai-compatible':undefined;const settings=await saveLlmSettings({enabled:typeof input.enabled==='boolean'?input.enabled:undefined,provider:provider as LlmProviderType|undefined,baseUrl:typeof input.baseUrl==='string'?input.baseUrl:undefined,apiKey:typeof input.apiKey==='string'?input.apiKey:undefined,model:typeof input.model==='string'?input.model:undefined});return json(response,200,{settings,status:await llmProviderStatus()});}
if(request.method==='DELETE'&&url.pathname==='/api/settings/llm'){const settings=await deleteLlmSettings();return json(response,200,{settings,status:await llmProviderStatus()});}
if(request.method==='POST'&&url.pathname==='/api/settings/llm/test')return json(response,200,await testLlmProvider());
if(request.method==='GET'&&url.pathname==='/api/sitrep')return json(response,200,{report:await service.sitrep()});
if(request.method==='GET'&&url.pathname==='/api/intelligence/timeline'){const state=await store.load();return json(response,200,{items:buildTimeline(state,await store.events(),Number(url.searchParams.get('limit')??100))});}
if(request.method==='GET'&&url.pathname==='/api/intelligence/graph')return json(response,200,buildKnowledgeGraph(await store.load()));
if(request.method==='GET'&&url.pathname==='/api/intelligence/daily-brief')return json(response,200,generateDailyBrief(await store.load()));
if(request.method==='GET'&&url.pathname==='/api/intelligence/insights')return json(response,200,{items:generateInsights(await store.load())});
if(request.method==='GET'&&url.pathname==='/api/intelligence/context')return json(response,200,{query:url.searchParams.get('q')??'',matches:resolveContext(await store.load(),url.searchParams.get('q')??'')});
if(request.method==='GET'&&url.pathname==='/api/career-inbox'){const state=await inbox.load();return json(response,200,{...state,connections:await connectionStatus(),watchFolder:await watchFolder.status()});}
if(request.method==='POST'&&url.pathname==='/api/career-inbox/sync')return json(response,200,await syncCareerInbox());
if(request.method==='POST'&&url.pathname==='/api/career-inbox/capture'){const input=await body(request);const format=text(input.format,'format') as CaptureFormat;if(!['eml','text','txt','msg'].includes(format))throw new Error('Unsupported capture format');return json(response,201,await captureCareerMessage({format,filename:typeof input.filename==='string'?input.filename:undefined,content:text(input.content,'content')}));}
if(request.method==='POST'&&url.pathname==='/api/career-inbox/capture-bulk'){const input=await body(request);if(!Array.isArray(input.items))throw new Error('items array is required');if(input.items.length>50)throw new Error('Maximum 50 messages per batch');let added=0,duplicates=0;const errors:{filename?:string;error:string}[]=[];for(const raw of input.items){try{if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new Error('Invalid item');const item=raw as Record<string,unknown>;const format=text(item.format,'format') as CaptureFormat;if(!['eml','text','txt','msg'].includes(format))throw new Error('Unsupported capture format');const result=await captureCareerMessage({format,filename:typeof item.filename==='string'?item.filename:undefined,content:text(item.content,'content')});if(result.added)added++;else duplicates++;}catch(error){const item=raw&&typeof raw==='object'&&!Array.isArray(raw)?raw as Record<string,unknown>:{};errors.push({filename:typeof item.filename==='string'?item.filename:undefined,error:error instanceof Error?error.message:String(error)});}}return json(response,201,{processed:input.items.length,added,duplicates,errors});}
if(request.method==='GET'&&url.pathname==='/api/career-inbox/watch-folder')return json(response,200,await watchFolder.status());
if(request.method==='POST'&&url.pathname==='/api/career-inbox/watch-folder'){const input=await body(request);const enabled=input.enabled===true;const folder=typeof input.folder==='string'&&input.folder.trim()?input.folder.trim():undefined;return json(response,200,await watchFolder.configure(folder,enabled));}
if(request.method==='POST'&&url.pathname==='/api/career-inbox/watch-folder/scan')return json(response,200,await watchFolder.scan());
if(request.method==='GET'&&url.pathname==='/api/oauth/status')return json(response,200,{connections:await connectionStatus()});
const connect=url.pathname.match(/^\/api\/oauth\/(gmail|outlook)\/connect$/);if(request.method==='GET'&&connect)return redirect(response,await beginOAuth(connect[1] as OAuthProvider));
const remove=url.pathname.match(/^\/api\/oauth\/(gmail|outlook)$/);if(request.method==='DELETE'&&remove){await disconnect(remove[1] as OAuthProvider);return json(response,200,{ok:true});}
if(request.method==='GET'&&url.pathname==='/api/oauth/callback'){const code=text(url.searchParams.get('code'),'code');const stateId=text(url.searchParams.get('state'),'state');const provider=await completeOAuth(code,stateId);return redirect(response,`http://127.0.0.1:5173/career-inbox.html?connected=${provider}`);}
const apply=url.pathname.match(/^\/api\/career-inbox\/([^/]+)\/apply$/);if(request.method==='POST'&&apply){const state=await inbox.load();const message=state.messages.find(item=>item.id===apply[1]);if(!message)throw new Error('Email not found');if(message.linkedJobId&&message.suggestedStatus)await service.updateJob(message.linkedJobId,message.suggestedStatus,message.suggestedAction);message.handled=true;await inbox.save(state);return json(response,200,{message});}
const ignore=url.pathname.match(/^\/api\/career-inbox\/([^/]+)\/ignore$/);if(request.method==='POST'&&ignore){const state=await inbox.load();const message=state.messages.find(item=>item.id===ignore[1]);if(!message)throw new Error('Email not found');message.handled=true;await inbox.save(state);return json(response,200,{message});}
if(request.method==='POST'&&url.pathname==='/api/projects'){const input=await body(request);return json(response,201,await service.addProject(text(input.name,'name'),(input.priority as Priority|undefined)??'P1'));}
if(request.method==='POST'&&url.pathname==='/api/actions'){const input=await body(request);return json(response,201,await service.addAction(text(input.title,'title'),(input.priority as Priority|undefined)??'P1',typeof input.projectId==='string'&&input.projectId?input.projectId:undefined));}
if(request.method==='POST'&&url.pathname==='/api/jobs'){const input=await body(request);return json(response,201,await service.addJob(text(input.company,'company'),text(input.role,'role'),typeof input.description==='string'?input.description:''));}
if(request.method==='POST'&&url.pathname==='/api/research'){const input=await body(request);return json(response,201,await service.addResearch(text(input.question,'question'),typeof input.projectId==='string'&&input.projectId?input.projectId:undefined));}
const project=url.pathname.match(/^\/api\/projects\/([^/]+)$/);if(request.method==='PATCH'&&project){const input=await body(request);return json(response,200,await service.updateProject(project[1],text(input.status,'status') as Status,typeof input.nextAction==='string'?input.nextAction:undefined));}
const job=url.pathname.match(/^\/api\/jobs\/([^/]+)$/);if(request.method==='PATCH'&&job){const input=await body(request);return json(response,200,await service.updateJob(job[1],text(input.status,'status') as JobStatus,typeof input.nextAction==='string'?input.nextAction:undefined));}
const touch=url.pathname.match(/^\/api\/jobs\/([^/]+)\/touch$/);if(request.method==='POST'&&touch){const input=await body(request);return json(response,200,await service.touchJob(touch[1],typeof input.note==='string'?input.note:undefined));}
const action=url.pathname.match(/^\/api\/actions\/([^/]+)\/complete$/);if(request.method==='POST'&&action){const input=await body(request);return json(response,200,await service.execute(action[1],typeof input.outcome==='string'&&input.outcome.trim()?input.outcome.trim():'Completed'));}
const evidence=url.pathname.match(/^\/api\/research\/([^/]+)\/evidence$/);if(request.method==='POST'&&evidence){const input=await body(request);return json(response,201,await service.addEvidence(evidence[1],text(input.title,'title'),text(input.url,'url'),(input.sourceType as 'primary'|'secondary'|undefined)??'secondary',typeof input.note==='string'?input.note:undefined));}
const synthesis=url.pathname.match(/^\/api\/research\/([^/]+)\/synthesize$/);if(request.method==='POST'&&synthesis){const input=await body(request);return json(response,201,await service.synthesizeResearch(synthesis[1],text(input.summary,'summary')));}
return json(response,404,{error:'Not found'});}catch(error){return json(response,400,{error:error instanceof Error?error.message:String(error)});}}
export function createApiServer(){watchFolder.start();return createServer((request,response)=>void handleApi(request,response));}
if(process.argv[1]?.endsWith('api.js')){const port=Number(process.env.MUNIN_API_PORT??4310);createApiServer().listen(port,'127.0.0.1',()=>console.log(`Munin API running at http://127.0.0.1:${port}`));}