export type BrandMarkId='aj-master'|'munin-seal'|'odin-symbol'|'document-seal';
export type BrandMark={id:BrandMarkId;name:string;purpose:string;assetRequired:boolean;allowedUses:string[];forbiddenUses:string[];locked:true};

export const BRAND_CANON={
  version:'AJ-BRAND-CANON-2.1',owner:'André Jardim',locked:true,
  doctrine:'Nordic influence belongs to the identity system, not to every illustration. Editorial content must look like executive innovation/financial-infrastructure publishing, never fantasy-Nordic decoration.',
  identity:{
    primaryMark:'aj-master' as BrandMarkId,
    rule:'The AJ master mark is immutable artwork and is never generated by an image model. It may only be used in explicitly requested brand artifacts, never as the default LinkedIn editorial signature.',
    fallback:'LinkedIn editorial visuals remain unbranded by default. Never create a placeholder AJ.',
    muninRule:'Munin uses only its approved raven seal asset. It is a product mark and is not a personal LinkedIn signature.'
  },
  palette:{base:['near-black #080B10','charcoal #11161D','deep navy-black #07111F'],neutral:['off-white','cool gray','gunmetal','brushed silver'],primaryAccent:['restrained cold/electric blue'],exceptionAccent:['muted bronze/gold — maximum 10% of image and only when conceptually justified']},
  editorial:{format:'4:5 portrait',defaultText:'no text inside generated artwork',composition:'one dominant metaphor/object, strong negative space, magazine-grade composition, controlled cinematic light, restrained depth',tone:['premium editorial','executive','strategic','financial infrastructure','technology with restraint','minimal'],allowedFamilies:['architectural precision','abstract physical metaphor','machined object','glass/metal structure','subtle network/infrastructure geometry'],never:['career-consulting infographic style','white-background diagram as default','cyberpunk advertising','AI hologram cliché','fantasy Nordic scene','decorative runes','compass imagery','crypto coins','blockchain hexagon cliché','multiple unrelated icons','gold-dominant luxury aesthetic','HUD/interface graphics','generic business people','AJ logo','AJ monogram','initials','personal logo','watermark','signature','branding marks']},
  marks:[
    {id:'aj-master',name:'AJ Master Mark',purpose:'personal executive signature for explicitly branded artifacts only',assetRequired:true,allowedUses:['explicitly requested profile/cover brand application','explicitly requested document signature'],forbiddenUses:['AI generation','redrawing','geometry changes','decorative centerpiece','rune improvisation','default LinkedIn editorial artwork','automatic social watermark'],locked:true},
    {id:'munin-seal',name:'Munin Raven Seal',purpose:'Munin product identity',assetRequired:true,allowedUses:['Munin product UI','Munin documentation','Munin-specific communication'],forbiddenUses:['default LinkedIn personal signature','AI-generated raven substitute','compass substitute'],locked:true},
    {id:'odin-symbol',name:'Odin Strategy Symbol',purpose:'optional strategy-system marker',assetRequired:true,allowedUses:['specific strategy artifacts only'],forbiddenUses:['default social watermark','decorative rune filler'],locked:true},
    {id:'document-seal',name:'Document Seal',purpose:'formal long-form identity',assetRequired:true,allowedUses:['white papers','formal reports','presentation covers'],forbiddenUses:['default social watermark'],locked:true}
  ] satisfies BrandMark[],
  social:{defaultMark:null,placement:'none by default',logoMaxWidthPercent:0,logoOpacity:'0% by default',workflow:['generate clean editorial artwork with no logo','validate against editorial exclusions','publish unbranded by default','apply an approved brand asset only when explicitly requested by the user']},
  legacyPolicy:'Previously published visuals are historical and must not be retroactively rewritten. Canon v2.1 applies to new work from 2026-08-18 onward.'
} as const;

export function editorialBrandPrompt(){return `AJ EDITORIAL SYSTEM v2.1 — LOCKED. Create ONLY clean editorial artwork. DO NOT generate or include AJ, any logo, initials, monogram, rune, seal, signature, watermark, personal branding or branding marks. LinkedIn editorial visuals are unbranded by default. Visual language: ${BRAND_CANON.editorial.tone.join(', ')}. Palette: ${BRAND_CANON.palette.base.join(', ')} with ${BRAND_CANON.palette.primaryAccent.join(', ')}; gold/bronze is exceptional and may never dominate. Composition: ${BRAND_CANON.editorial.composition}. Avoid absolutely: ${BRAND_CANON.editorial.never.join(', ')}.`;}

export function brandAssetRequirement(mark:BrandMarkId='aj-master'){const selected=BRAND_CANON.marks.find(x=>x.id===mark)!;return {mark:selected.id,assetRequired:selected.assetRequired,rule:BRAND_CANON.identity.rule,fallback:BRAND_CANON.identity.fallback};}
