import type { CareerEmail, CareerEmailCategory } from './career-inbox.js';
import type { JobOpportunity, JobStatus } from './types.js';

export interface CareerProcessSignal { id:string; at:string; category:CareerEmailCategory; subject:string; from?:string; confidence:number; }
export interface CareerProcess { job:JobOpportunity; signals:CareerProcessSignal[]; lastSignalAt?:string; suggestedStatus?:JobStatus; suggestedAction?:string; automation:'auto'|'review'|'none'; }
export interface CareerBrief { generatedAt:string; interviews:CareerProcess[]; followUps:CareerProcess[]; attention:CareerProcess[]; stale:CareerProcess[]; counts:{active:number;interviews:number;followUps:number;attention:number;stale:number}; }
const terminal=new Set<JobStatus>(['offer','rejected','closed']);
const statusRank:Record<JobStatus,number>={discovered:0,investigating:1,applied:2,interview:3,offer:4,rejected:4,closed:5};
const highConfidence=new Set<CareerEmailCategory>(['application_confirmation','interview_invite','rejection','offer']);
function processFor(job:JobOpportunity,messages:CareerEmail[]):CareerProcess{const signals=messages.filter(m=>m.linkedJobId===job.id).sort((a,b)=>Date.parse(b.receivedAt)-Date.parse(a.receivedAt)).map(m=>({id:m.id,at:m.receivedAt,category:m.category,subject:m.subject,from:m.fromName??m.fromEmail,confidence:m.confidence}));const latest=messages.filter(m=>m.linkedJobId===job.id).sort((a,b)=>Date.parse(b.receivedAt)-Date.parse(a.receivedAt))[0];const advancing=latest?.suggestedStatus&&statusRank[latest.suggestedStatus]>=statusRank[job.status]?latest.suggestedStatus:undefined;const automation=latest&&advancing&&latest.confidence>=.9&&highConfidence.has(latest.category)?'auto':latest&&advancing?'review':'none';return{job,signals,lastSignalAt:signals[0]?.at,suggestedStatus:advancing,suggestedAction:latest?.suggestedAction,automation};}
export function buildCareerProcesses(jobs:JobOpportunity[],messages:CareerEmail[]):CareerProcess[]{return jobs.map(j=>processFor(j,messages)).sort((a,b)=>Date.parse(b.lastSignalAt??b.job.updatedAt)-Date.parse(a.lastSignalAt??a.job.updatedAt));}
export function buildCareerBrief(jobs:JobOpportunity[],messages:CareerEmail[],now=new Date()):CareerBrief{const processes=buildCareerProcesses(jobs,messages);const active=processes.filter(p=>!terminal.has(p.job.status));const interviews=active.filter(p=>p.job.status==='interview'||p.suggestedStatus==='interview');const followUps=active.filter(p=>p.job.followUpAt&&Date.parse(p.job.followUpAt)<=now.getTime());const attention=active.filter(p=>p.automation==='review'||p.suggestedStatus==='offer');const stale=active.filter(p=>(now.getTime()-Date.parse(p.lastSignalAt??p.job.updatedAt))/86400000>=7&&!followUps.includes(p));return{generatedAt:now.toISOString(),interviews,followUps,attention,stale,counts:{active:active.length,interviews:interviews.length,followUps:followUps.length,attention:attention.length,stale:stale.length}};}
