import { contextBriefForConsumer } from './context-memory.js';
import { completeWithLlm } from './llm-provider.js';
import { CareerVisionExtractor } from './career-vision-extractor.js';
import { scoreCareerMatch, type CareerIntakeInput } from './career-intake.js';

export type CareerApplyRecommendation='CANDIDATAR'|'AVALIAR'|'NAO_PRIORIZAR';
export interface CareerIntakeAnalysis { company?:string; role?:string; match:number; recommendation:CareerApplyRecommendation; summary:string; strengths:string[]; gaps:string[]; nextSteps:string[]; source:'url'|'text'|'screenshot'|'mixed'; extractedText?:string; sourceUrl?:string; visionUsed:boolean; evidence:string[]; providerMode:'llm'|'heuristic'; }

function stripHtml(html:string){return html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/\s+/g,' ').trim().slice(0,22000)}
async function fetchUrlText(url:string){try{const parsed=new URL(url);if(!/^https?:$/.test(parsed.protocol))throw new Error('URL inválida');const response=await fetch(parsed.toString(),{headers:{'user-agent':'Mozilla/5.0 MuninCareer/1.0','accept':'text/html,application/xhtml+xml'},redirect:'follow',signal:AbortSignal.timeout(12000)});if(!response.ok)return {text:'',evidence:`URL retornou HTTP ${response.status}.`};const type=response.headers.get('content-type')??'';if(!type.includes('text'))return {text:'',evidence:`URL retornou conteúdo ${type||'não textual'}.`};const text=stripHtml(await response.text());return {text,evidence:text?`Página pública lida (${text.length} caracteres).`:'Página pública sem texto útil.'};}catch(error){return {text:'',evidence:`Leitura direta da URL falhou: ${error instanceof Error?error.message:String(error)}.`}}}
function cleanArray(v:unknown){return Array.isArray(v)?v.filter((x):x is string=>typeof x==='string').map(x=>x.trim()).filter(Boolean).slice(0,8):[]}
function parse(raw:string,base:Omit<CareerIntakeAnalysis,'match'|'recommendation'|'summary'|'strengths'|'gaps'|'nextSteps'|'providerMode'>):CareerIntakeAnalysis|undefined{try{const value=JSON.parse(raw.trim().replace(/^```json\s*/i,'').replace(/```$/,'').trim()) as Record<string,unknown>;if(!value||typeof value!=='object')return;const match=Math.max(0,Math.min(100,Math.round(Number(value.match)||0)));const recommendation=typeof value.recommendation==='string'?value.recommendation:'';const rec:CareerApplyRecommendation=recommendation==='CANDIDATAR'||recommendation==='NAO_PRIORIZAR'?recommendation:'AVALIAR';return {...base,company:typeof value.company==='string'?value.company.trim()||undefined:undefined,role:typeof value.role==='string'?value.role.trim()||undefined:undefined,match,recommendation:rec,summary:typeof value.summary==='string'&&value.summary.trim()?value.summary.trim():'Análise concluída.',strengths:cleanArray(value.strengths),gaps:cleanArray(value.gaps),nextSteps:cleanArray(value.nextSteps),evidence:[...base.evidence,...cleanArray(value.evidence)].slice(0,10),providerMode:'llm'};}catch{return undefined}}
function withDeadline<T>(promise:Promise<T>,ms:number):Promise<T>{return new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('CAREER_MATCH_TIMEOUT')),ms);promise.then(value=>{clearTimeout(timer);resolve(value)},error=>{clearTimeout(timer);reject(error)})})}
export async function analyzeCareerIntake(input:CareerIntakeInput):Promise<CareerIntakeAnalysis>{const evidence:string[]=[];let urlText='';let extracted=input.extractedText??input.text??'';let visionUsed=false;const suppliedText=Boolean(extracted.trim());if(input.url&&!suppliedText){const result=await fetchUrlText(input.url);urlText=result.text;evidence.push(result.evidence)}else if(input.url&&suppliedText){evidence.push('Texto da vaga fornecido; leitura remota da URL não bloqueou a análise.')}if((input.source==='screenshot'||input.source==='image')&&input.image?.dataBase64&&!extracted){try{extracted=await new CareerVisionExtractor().extract(input);visionUsed=true;evidence.push('Screenshot interpretado por provider multimodal.');}catch(error){evidence.push(`Screenshot recebido, mas leitura visual indisponível: ${error instanceof Error?error.message:String(error)}`)}}const corpus=[input.title,input.company,input.role,extracted,urlText,input.url].filter(Boolean).join('\n\n').slice(0,30000);if(!corpus)throw new Error('CAREER_INTAKE_CONTENT_REQUIRED');const source:CareerIntakeAnalysis['source']=[input.url,input.text||input.extractedText,input.image?.dataBase64].filter(Boolean).length>1?'mixed':input.image?.dataBase64?'screenshot':input.url?'url':'text';const base={source,extractedText:extracted||undefined,sourceUrl:input.url,visionUsed,evidence};const memory=await contextBriefForConsumer('career');const system='Você é o Career Match Engine do Munin. Compare a vaga com o perfil governado. Seja conservador. Não invente salário, senioridade ou requisitos. Responda SOMENTE JSON válido com company, role, match (0-100), recommendation (CANDIDATAR|AVALIAR|NAO_PRIORIZAR), summary, strengths[], gaps[], nextSteps[], evidence[]. CANDIDATAR exige aderência forte; AVALIAR indica incerteza; NAO_PRIORIZAR indica baixo alinhamento.';try{const budget=Math.max(3000,Number(process.env.MUNIN_CAREER_MATCH_TIMEOUT_MS??15000));const raw=await withDeadline(completeWithLlm(system,`Perfil governado:\n${JSON.stringify(memory.context)}\n\nVaga:\n${corpus}\n\nEvidências de ingestão:\n${evidence.join('\n')}`,2600),budget);const parsed=parse(raw,base);if(parsed)return parsed;}catch(error){evidence.push(error instanceof Error&&error.message==='CAREER_MATCH_TIMEOUT'?'Provider de IA excedeu o orçamento do Career Match; fallback local aplicado.':'Provider de IA indisponível; fallback local aplicado.')}const scored=scoreCareerMatch(corpus);const match=scored.score;return {...base,evidence:base.evidence,match,recommendation:match>=70?'CANDIDATAR':match>=40?'AVALIAR':'NAO_PRIORIZAR',summary:'Análise heurística local. O provider de IA não respondeu dentro do orçamento do Career Match.',strengths:scored.matchedSignals.slice(0,8).map(x=>`Sinal aderente: ${x}`),gaps:['A comparação semântica detalhada não ficou disponível nesta execução.'],nextSteps:[match>=40?'Revisar requisitos críticos antes de candidatar.':'Não priorizar sem evidência adicional de aderência.'],providerMode:'heuristic'};}
