import type { IncomingMessage, ServerResponse } from 'node:http';
import { CareerInboxStore } from './career-inbox.js';
import { careerCommandBrief, buildInterviewWarRooms, runCareerAutomation } from './career-automation.js';
import { fetchInterviewCalendar, googleCalendarReady } from './calendar-intelligence.js';
import { extractJobDiscoveries } from './job-discovery.js';
import { ContextStore } from './store.js';
import { json } from './http.js';
import { loadCareerApplicationPacket } from './career-application-packet.js';
export async function handleCareerIntelligence(request:IncomingMessage,response:ServerResponse):Promise<void>{if(request.method==='OPTIONS')return json(request,response,204,{});const url=new URL(request.url??'/','http://127.0.0.1');try{if(request.method==='GET'&&url.pathname==='/api/career-intelligence/brief')return json(request,response,200,await careerCommandBrief());if(request.method==='GET'&&url.pathname==='/api/career-intelligence/war-rooms')return json(request,response,200,{items:await buildInterviewWarRooms(),calendarReady:await googleCalendarReady()});if(request.method==='GET'&&url.pathname==='/api/career-intelligence/calendar')return json(request,response,200,{ready:await googleCalendarReady(),items:await fetchInterviewCalendar()});if(request.method==='GET'&&url.pathname==='/api/career-intelligence/application-packet')return json(request,response,200,await loadCareerApplicationPacket(url.searchParams.get('jobId')??''));if(request.method==='GET'&&url.pathname==='/api/career-intelligence/discoveries'){const state=await new ContextStore().load(),inbox=await new CareerInboxStore().load();return json(request,response,200,{items:extractJobDiscoveries(inbox.messages,state.jobs).slice(0,50)});}if(request.method==='POST'&&url.pathname==='/api/career-intelligence/automate')return json(request,response,200,await runCareerAutomation());return json(request,response,404,{error:'Not found'});}catch(error){return json(request,response,400,{error:error instanceof Error?error.message:String(error)})}}
