import { spawn } from 'node:child_process';
import { isAbsolute } from 'node:path';
import type { RuntimeCapability, RuntimeCapabilityRegistry } from './runtime-capability-seam.js';

export type ContentVideoAction='health'|'plan'|'generate';
export interface ContentVideoInput{action:ContentVideoAction;topic?:string;script?:string;language?:string;aspectRatio?:'16:9'|'9:16'|'1:1';outputDir?:string;provider?:'moneyprinterturbo'|'custom'}
export interface ContentVideoOutput{action:ContentVideoAction;ready:boolean;detail:string;policy:{enabled:boolean;runnerConfigured:boolean;automaticInstallAllowed:false;automaticPublishAllowed:false;paidDependencyRequired:false;humanApprovalRequired:true};request?:Record<string,unknown>;result?:unknown}

function policy(){const enabled=process.env.MUNIN_CONTENT_VIDEO_ENABLED==='1';const runner=process.env.MUNIN_CONTENT_VIDEO_RUNNER?.trim()??'';return{enabled,runnerConfigured:Boolean(runner),automaticInstallAllowed:false as const,automaticPublishAllowed:false as const,paidDependencyRequired:false as const,humanApprovalRequired:true as const};}
function requestFor(input:ContentVideoInput){if(!input.topic?.trim())throw new Error('topic is required');return{topic:input.topic.trim(),script:input.script?.trim()||undefined,language:input.language?.trim()||'pt-BR',aspectRatio:input.aspectRatio??'9:16',outputDir:input.outputDir,provider:input.provider??'moneyprinterturbo',requireHumanApproval:true,brandRules:{noLogo:true,noMonogram:true,noSignature:true,noWatermark:true}};}
function run(runner:string,request:Record<string,unknown>):Promise<unknown>{if(!isAbsolute(runner))throw new Error('MUNIN_CONTENT_VIDEO_RUNNER must be an absolute path');return new Promise((resolve,reject)=>{const child=spawn(runner,[],{stdio:['pipe','pipe','pipe'],shell:false,windowsHide:true,env:process.env});let stdout='',stderr='';child.stdout.setEncoding('utf8');child.stderr.setEncoding('utf8');child.stdout.on('data',value=>stdout+=value);child.stderr.on('data',value=>stderr+=value);child.once('error',reject);child.once('exit',code=>{if(code!==0)return reject(new Error(`Content video runner exited ${code}: ${stderr.trim().slice(0,800)}`));try{resolve(stdout.trim()?JSON.parse(stdout):{ok:true});}catch{resolve({ok:true,output:stdout.trim()});}});child.stdin.end(JSON.stringify(request));});}

export function createContentVideoCapability():RuntimeCapability<ContentVideoInput,ContentVideoOutput>{return{name:'media.content-video',async execute(input){const p=policy();if(input.action==='health')return{action:'health',ready:p.enabled&&p.runnerConfigured,policy:p,detail:p.enabled?(p.runnerConfigured?'Content video runner configured; human review remains mandatory.':'Configure MUNIN_CONTENT_VIDEO_RUNNER with a MoneyPrinterTurbo-compatible adapter.'):'Content video is opt-in; enable it only after the local runner is installed and reviewed.'};const request=requestFor(input);if(input.action==='plan')return{action:'plan',ready:p.enabled&&p.runnerConfigured,policy:p,detail:'Production request prepared without generating or publishing media.',request};if(!p.enabled)throw new Error('Content video capability is disabled');const runner=process.env.MUNIN_CONTENT_VIDEO_RUNNER?.trim();if(!runner)throw new Error('MUNIN_CONTENT_VIDEO_RUNNER is required');return{action:'generate',ready:true,policy:p,detail:'Draft video generated locally; publication remains blocked pending human review.',request,result:await run(runner,request)};}};}
export function registerContentVideoCapability(registry:RuntimeCapabilityRegistry):void{if(!registry.has('media.content-video'))registry.register(createContentVideoCapability());}
export function contentVideoPolicy(){return policy();}
