import { createServer,type IncomingMessage,type ServerResponse } from 'node:http';
import { contextBriefForConsumer,importContextSeed,loadContextMemory,previewContextSeed,queryContextMemory,publicContextSnapshot,type ContextConsumer,type MemoryScope } from './context-memory.js';
function json(res:ServerResponse,status:number,body:unknown){res.writeHead(status,{'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','access-control-allow-headers':'content-type','access-control-allow-methods':'GET,POST,OPTIONS'});res.end(JSON.stringify(body));}
async function body(req:IncomingMessage){const chunks:Buffer[]=[];let size=0;for await(const c of req){const b=Buffer.from(c);size+=b.length;if(size>6_000_000)throw new Error('Payload too large');chunks.push(b);}if(!chunks.length)return{};const parsed=JSON.parse(Buffer.concat(chunks).toString('utf8'));if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new Error('JSON object body required');return parsed as Record<string,unknown>;}
export async function handleContextMemory(req:IncomingMessage,res:ServerResponse){if(req.method==='OPTIONS')return json(res,204,{});const url=new URL(req.url??'/','http://127.0.0.1');try{
 if(req.method==='GET'&&url.pathname==='/api/context-memory'){const state=await loadContextMemory();return json(res,200,{state,summary:{sections:Object.keys(state.sections).length,imports:state.imports.length,scopes:Object.values(state.sections).reduce((a,s)=>(a[s.scope]=(a[s.scope]??0)+1,a),{} as Record<string,number>)}});}
 if(req.method==='POST'&&url.pathname==='/api/context-memory/preview'){const input=await body(req);return json(res,200,await previewContextSeed(input.seed));}
 if(req.method==='POST'&&url.pathname==='/api/context-memory/import'){const input=await body(req);return json(res,201,await importContextSeed(input.seed,{source:typeof input.source==='string'?input.source:'manual-seed-import',replaceConflicts:input.replaceConflicts===true}));}
 if(req.method==='GET'&&url.pathname==='/api/context-memory/query'){const q=url.searchParams.get('q')??'';const scopeParam=url.searchParams.get('scopes');const scopes=(scopeParam?scopeParam.split(','):['public-professional','private-operational']).filter(x=>['public-professional','private-operational','sensitive-private'].includes(x)) as MemoryScope[];return json(res,200,{query:q,results:await queryContextMemory(q,scopes)});}
 if(req.method==='GET'&&url.pathname==='/api/context-memory/public')return json(res,200,{sections:await publicContextSnapshot()});
 const consumer=url.pathname.match(/^\/api\/context-memory\/consumer\/(linkedin|career|sitrep|assistant)$/);if(req.method==='GET'&&consumer)return json(res,200,await contextBriefForConsumer(consumer[1] as ContextConsumer));
 return json(res,404,{error:'Not found'});
}catch(error){return json(res,400,{error:error instanceof Error?error.message:String(error)});}}
export function createContextMemoryServer(){return createServer((req,res)=>void handleContextMemory(req,res));}
if(process.argv[1]?.endsWith('context-memory-api.js')){const port=Number(process.env.MUNIN_CONTEXT_MEMORY_PORT??4314);createContextMemoryServer().listen(port,'127.0.0.1',()=>console.log(`Munin Context Memory API running at http://127.0.0.1:${port}`));}
