import { expandCareerAlert, careerAlertHealth } from './career-alert-extraction.js';
import { randomUUID } from 'node:crypto';
import { CareerInboxStore, classifyCareerEmail, type CareerEmail, type EmailProvider } from './career-inbox.js';
import { ContextStore } from './store.js';
import { accessToken, connectionStatus, OAuthReconnectRequiredError } from './oauth.js';
import { runCareerAutomation } from './career-automation.js';
import { promoteEmailActions } from './email-action-engine.js';

type GmailList = { messages?: Array<{id:string;threadId?:string}>; nextPageToken?:string };
type GmailPart = {mimeType?:string;body?:{data?:string};parts?:GmailPart[]};
type GmailMessage = { id:string; threadId?:string; internalDate?:string; snippet?:string; payload?:GmailPart & {headers?:Array<{name:string;value:string}>} };
type GraphRow = {id:string;conversationId?:string;subject?:string;bodyPreview?:string;receivedDateTime?:string;from?:{emailAddress?:{name?:string;address?:string}};body?:{contentType?:string;content?:string}};
type GraphList = { value?: GraphRow[]; '@odata.nextLink'?:string };
const DEFAULT_SYNC_DAYS=30,DEFAULT_MAX_MESSAGES=500;
function header(message:GmailMessage,name:string):string|undefined{return message.payload?.headers?.find(h=>h.name.toLowerCase()===name.toLowerCase())?.value}function bearer(token:string):Record<string,string>{return{authorization:`Bearer ${token}`}}function sinceIso(days:number):string{return new Date(Date.now()-days*86400000).toISOString()}function mailbox(value:string):{name?:string;email:string}{const email=value.match(/<([^>]+)>/)?.[1]?.trim()??value.trim();const name=value.replace(/<[^>]+>/,'').replace(/^['"]|['"]$/g,'').trim()||undefined;return{name,email}}function forwardedIdentity(subject:string,snippet:string,outerFrom:string){const text=`${subject}\n${snippet}`;const forwardMarker=/\b(?:fw|fwd|enc|encaminhada?)\s*:/i.test(subject)||/(?:forwarded message|mensagem encaminhada|mensagem original)/i.test(text);const originalFrom=text.match(/(?:^|[\n\r]|\s)(?:from|de)\s*:\s*([^\n\r]+?)(?=\s+(?:sent|enviado|date|data|to|para|subject|assunto)\s*:|$)/i)?.[1]?.trim();const originalSubject=text.match(/(?:^|[\n\r]|\s)(?:subject|assunto)\s*:\s*([^\n\r]+)/i)?.[1]?.trim();if(!forwardMarker||!originalFrom)return{subject,snippet,fromEmail:outerFrom,forwarded:false};const parsed=mailbox(originalFrom);return{subject:originalSubject||subject.replace(/^\s*(?:fw|fwd|enc)\s*:\s*/i,''),snippet,fromName:parsed.name,fromEmail:parsed.email,forwarded:true}}

/** Multipart alternatives are not concatenated, avoiding duplicate plaintext/HTML cards. */
export function gmailAlertBody(payload?:GmailPart):{text:string;html:boolean}{
 const html:string[]=[];const text:string[]=[];
 function visit(part?:GmailPart,depth=0){if(!part||depth>20)return;if(part.body?.data&&(part.mimeType==='text/html'||part.mimeType==='text/plain')){const decoded=Buffer.from(part.body.data.slice(0,700000),'base64url').toString('utf8');(part.mimeType==='text/html'?html:text).push(decoded);}for(const child of (part.parts??[]).slice(0,100))visit(child,depth+1)}
 visit(payload);return {text:(html.length?html:text).join('\n').slice(0,500001),html:html.length>0};
}
export async function fetchGmail(token:string,days=DEFAULT_SYNC_DAYS,max=DEFAULT_MAX_MESSAGES):Promise<CareerEmail[]>{const refs:Array<{id:string;threadId?:string}>=[];let pageToken:string|undefined;while(refs.length<max){const params=new URLSearchParams({maxResults:String(Math.min(100,max-refs.length)),q:`newer_than:${days}d -in:spam -in:trash`});if(pageToken)params.set('pageToken',pageToken);const list=await fetch(`https://gmail.googleapis.com/gmail/v1/users/me/messages?${params}`,{headers:bearer(token),signal:AbortSignal.timeout(20000)});if(!list.ok)throw new Error(`Gmail sync failed: ${list.status}`);const payload=await list.json() as GmailList;refs.push(...(payload.messages??[]));pageToken=payload.nextPageToken;if(!pageToken)break}const messages:CareerEmail[]=[];const jobs=(await new ContextStore().load()).jobs;const cached=(await new CareerInboxStore().load()).messages;for(const ref of refs.slice(0,max)){const response=await fetch(`https://gmail.googleapis.com/gmail/v1/users/me/messages/${ref.id}?format=metadata&metadataHeaders=Subject&metadataHeaders=From&metadataHeaders=Date`,{headers:bearer(token),signal:AbortSignal.timeout(20000)});if(!response.ok)throw new Error(`Gmail message fetch failed: ${response.status}`);const raw=await response.json() as GmailMessage;const outer=mailbox(header(raw,'From')??'');const identity=forwardedIdentity(header(raw,'Subject')??'(sem assunto)',raw.snippet??'',outer.email);const classified=classifyCareerEmail({subject:identity.subject,snippet:identity.snippet,fromEmail:identity.fromEmail},jobs);const message:CareerEmail={id:randomUUID(),provider:identity.forwarded?'outlook':'gmail',providerMessageId:`gmail:${raw.id}`,threadId:raw.threadId,fromName:identity.fromName??outer.name,fromEmail:identity.fromEmail,receivedAt:new Date(Number(raw.internalDate??Date.now())).toISOString(),handled:false,...classified};
if(message.category==='job_alert'){
  const previous=cached.find(item=>item.providerMessageId===message.providerMessageId&&item.provider===message.provider);
  const children=cached.filter(item=>item.sourceEmailId===message.providerMessageId&&item.provider===message.provider);
  if(previous?.alertExtraction?.count&&children.length===previous.alertExtraction.count){messages.push({...message,alertExtraction:previous.alertExtraction},...children);continue;}
  try{const full=await fetch(`https://gmail.googleapis.com/gmail/v1/users/me/messages/${ref.id}?format=full`,{headers:bearer(token),signal:AbortSignal.timeout(20000)});if(!full.ok)throw new Error('Alert body unavailable');const content=gmailAlertBody((await full.json() as GmailMessage).payload);messages.push(...expandCareerAlert(message,content.text,content.html));}
  catch{messages.push({...message,alertExtraction:{count:0,incomplete:true}});}
}else messages.push(message)}return messages}
export async function fetchOutlook(token:string,days=DEFAULT_SYNC_DAYS,max=DEFAULT_MAX_MESSAGES):Promise<CareerEmail[]>{
 const rows:GraphRow[]=[];
 let next=`https://graph.microsoft.com/v1.0/me/messages?$top=${Math.min(100,max)}&$orderby=receivedDateTime%20desc&$select=id,conversationId,subject,bodyPreview,receivedDateTime,from&${encodeURI(`$filter=receivedDateTime ge ${sinceIso(days)}`)}`;
 while(next&&rows.length<max){const response=await fetch(next,{headers:bearer(token),signal:AbortSignal.timeout(20000)});if(!response.ok)throw new Error(`Outlook sync failed: ${response.status}`);const payload=await response.json() as GraphList;rows.push(...(payload.value??[]));next=payload['@odata.nextLink']??''}
 const jobs=(await new ContextStore().load()).jobs;const messages:CareerEmail[]=[];const cached=(await new CareerInboxStore().load()).messages;
 for(const raw of rows.slice(0,max)){
  const subject=raw.subject??'(sem assunto)',address=raw.from?.emailAddress?.address;
  const classified=classifyCareerEmail({subject,snippet:raw.bodyPreview??'',fromEmail:address},jobs);
  const message:CareerEmail={id:randomUUID(),provider:'outlook',providerMessageId:raw.id,threadId:raw.conversationId,fromName:raw.from?.emailAddress?.name,fromEmail:address,receivedAt:raw.receivedDateTime??new Date().toISOString(),handled:false,...classified};
  if(message.category==='job_alert'){
   const previous=cached.find(item=>item.providerMessageId===message.providerMessageId&&item.provider===message.provider);
   const children=cached.filter(item=>item.sourceEmailId===message.providerMessageId&&item.provider===message.provider);
   if(previous?.alertExtraction?.count&&children.length===previous.alertExtraction.count){messages.push({...message,alertExtraction:previous.alertExtraction},...children);continue;}
   try{const response=await fetch(`https://graph.microsoft.com/v1.0/me/messages/${encodeURIComponent(raw.id)}?$select=body`,{headers:bearer(token),signal:AbortSignal.timeout(20000)});if(!response.ok)throw new Error('Alert body unavailable');const full=await response.json() as GraphRow;messages.push(...expandCareerAlert(message,full.body?.content??'',full.body?.contentType?.toLowerCase()==='html'));}
   catch{messages.push({...message,alertExtraction:{count:0,incomplete:true}});}
  }else messages.push(message);
 }
 return messages;
}
export async function syncCareerInbox(days=DEFAULT_SYNC_DAYS):Promise<{providers:string[];added:number;duplicates:number;totalFetched:number;windowDays:number;needsConnection?:boolean;alertHealth?:ReturnType<typeof careerAlertHealth>;automation?:Awaited<ReturnType<typeof runCareerAutomation>>;emailActions?:Awaited<ReturnType<typeof promoteEmailActions>>}>{const messages:CareerEmail[]=[],providers:string[]=[];const status=await connectionStatus();let needsConnection=false;let gmailToken=process.env.MUNIN_GMAIL_ACCESS_TOKEN;let outlookToken=process.env.MUNIN_OUTLOOK_ACCESS_TOKEN;try{gmailToken??=status.find(x=>x.provider==='gmail'&&x.connected)?await accessToken('gmail'):undefined}catch(error){if(error instanceof OAuthReconnectRequiredError)needsConnection=true;else throw error}try{outlookToken??=status.find(x=>x.provider==='outlook'&&x.connected)?await accessToken('outlook'):undefined}catch(error){if(error instanceof OAuthReconnectRequiredError)needsConnection=true;else throw error}if(gmailToken){messages.push(...await fetchGmail(gmailToken,days));providers.push('gmail')}if(outlookToken){messages.push(...await fetchOutlook(outlookToken,days));providers.push('outlook')}if(!providers.length)return{providers:[],added:0,duplicates:0,totalFetched:0,windowDays:days,needsConnection:true};const result=await new CareerInboxStore().upsert(messages);const automation=await runCareerAutomation();const emailActions=await promoteEmailActions();return{...result,alertHealth:careerAlertHealth(messages),providers,totalFetched:messages.filter(m=>!m.sourceEmailId).length,windowDays:days,needsConnection:needsConnection||undefined,automation,emailActions}}
