import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { randomUUID } from 'node:crypto';
import { completeWithLlm } from './llm-provider.js';

const execFileAsync=promisify(execFile);
export type EngineeringPhase='inspect'|'plan'|'edit'|'validate'|'repair'|'commit'|'push'|'pr'|'ci'|'completed'|'needs_user'|'failed';
export type EngineeringEvent={phase:EngineeringPhase;message:string;at:string;evidence?:string};
export type EngineeringResult={status:'completed'|'needs_user'|'failed';objective:string;branch?:string;commit?:string;pullRequest?:string;worktree?:string;changedFiles:string[];events:EngineeringEvent[];validation?:string;delivery?:'pull-request'|'pushed-branch'|'local-commit';message:string};
type ReadPlan={strategy?:string;filesToRead?:string[]};
type EditPlan={summary?:string;changes?:{path:string;content:string}[]};

const ignoredDirs=new Set(['.git','node_modules','dist','coverage','data','.vite']);
function event(phase:EngineeringPhase,message:string,evidence?:string):EngineeringEvent{return {phase,message,at:new Date().toISOString(),evidence}}
function cleanJson<T>(raw:string):T{const text=raw.trim().replace(/^```json\s*/i,'').replace(/```$/,'').trim();return JSON.parse(text) as T}
function slug(value:string){return value.toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,42)||'build'}
function safeRelative(value:string){const normalized=value.replace(/\\/g,'/').replace(/^\.\//,'');if(!normalized||path.posix.isAbsolute(normalized)||normalized.startsWith('../')||normalized.includes('/../'))throw new Error(`Unsafe path: ${value}`);if(normalized==='.env'||normalized.startsWith('.env.')||normalized.startsWith('.git/')||normalized.startsWith('data/runtime/')||normalized.includes('node_modules/'))throw new Error(`Protected path: ${value}`);return normalized}
async function run(file:string,args:string[],cwd:string,timeout=180_000){try{const result=await execFileAsync(file,args,{cwd,timeout,maxBuffer:8*1024*1024,windowsHide:true});return {ok:true,stdout:String(result.stdout??''),stderr:String(result.stderr??'')}}catch(error:any){return {ok:false,stdout:String(error?.stdout??''),stderr:String(error?.stderr??error?.message??error),code:error?.code}}}
async function filesUnder(root:string){const out:string[]=[];async function walk(dir:string){if(out.length>=350)return;for(const entry of await fs.readdir(dir,{withFileTypes:true})){if(out.length>=350)break;if(entry.name.startsWith('.')&&entry.name!=='.github')continue;if(entry.isDirectory()&&ignoredDirs.has(entry.name))continue;const abs=path.join(dir,entry.name);if(entry.isDirectory())await walk(abs);else{const rel=path.relative(root,abs).replace(/\\/g,'/');if(!/\.(ts|tsx|js|mjs|json|md|yml|yaml|css|html|ps1)$/.test(rel))continue;out.push(rel)}}}await walk(root);return out}
async function readSelected(root:string,items:string[]){let budget=100_000;const blocks:string[]=[];for(const raw of items.slice(0,12)){const rel=safeRelative(raw);const abs=path.join(root,rel);try{const stat=await fs.stat(abs);if(!stat.isFile()||stat.size>50_000)continue;const text=await fs.readFile(abs,'utf8');const clipped=text.slice(0,Math.max(0,budget));budget-=clipped.length;blocks.push(`FILE: ${rel}\n${clipped}`);if(budget<=0)break}catch{/* planner may propose a new path */}}return blocks.join('\n\n---\n\n')}
async function applyChanges(root:string,changes:EditPlan['changes']){const changed:string[]=[];for(const item of (changes??[]).slice(0,8)){if(!item||typeof item.path!=='string'||typeof item.content!=='string')continue;const rel=safeRelative(item.path);if(item.content.length>180_000)throw new Error(`Generated file too large: ${rel}`);const abs=path.join(root,rel);await fs.mkdir(path.dirname(abs),{recursive:true});await fs.writeFile(abs,item.content,'utf8');changed.push(rel)}if(!changed.length)throw new Error('Engineering provider returned no valid file changes.');return changed}
async function attachDependencies(root:string,worktree:string){const source=path.join(root,'node_modules');const target=path.join(worktree,'node_modules');try{const stat=await fs.stat(source);if(!stat.isDirectory())return false;await fs.symlink(source,target,process.platform==='win32'?'junction':'dir');return true}catch{return false}}
async function chooseBase(root:string){const main=await run('git',['rev-parse','--verify','main'],root,20_000);return main.ok?'main':'HEAD'}
function firstUrl(text:string){return text.match(/https:\/\/github\.com\/[^\s]+\/pull\/\d+/)?.[0]}

const plannerSystem=`You are Munin's software engineering planner. Return ONLY JSON: {"strategy":"...","filesToRead":["path"]}. Select at most 12 files from the provided repository tree that are necessary for the objective. Never request secrets, .env, .git, node_modules or data/runtime. Prefer the smallest coherent change.`;
const editorSystem=`You are Munin's autonomous builder. Return ONLY JSON: {"summary":"short commit summary","changes":[{"path":"relative/path","content":"COMPLETE UTF-8 FILE CONTENT"}]}. Make the smallest production-quality change that satisfies the objective. At most 8 files. Never touch secrets, .env, .git, node_modules or data/runtime. Preserve existing architecture and tests. Do not return patches: return complete contents only.`;
const repairSystem=`You are Munin's repair agent. A previous edit failed npm test. Return ONLY JSON in the same {summary,changes[]} shape, with complete contents only for files that must change. Fix the failure without weakening tests or deleting functionality.`;

export class EngineeringAgentRuntime{
 constructor(private readonly repo=process.cwd()){}
 async execute(objective:string):Promise<EngineeringResult>{const events:EngineeringEvent[]=[];const changed=new Set<string>();let worktree='';let branch='';
  try{
   const top=await run('git',['rev-parse','--show-toplevel'],this.repo,20_000);if(!top.ok)return {status:'needs_user',objective,changedFiles:[],events:[event('needs_user','Git repository unavailable.',top.stderr)],message:'Munin precisa rodar dentro de um repositório Git.'};
   const root=top.stdout.trim();const base=await chooseBase(root);events.push(event('inspect','Repository located.',`${root} · base ${base}`));
   const tree=await filesUnder(root);const id=randomUUID().slice(0,8);worktree=path.join(os.tmpdir(),'munin-engineering',id);await fs.mkdir(path.dirname(worktree),{recursive:true});
   const add=await run('git',['worktree','add','--detach',worktree,base],root,60_000);if(!add.ok)throw new Error(`git worktree failed: ${add.stderr}`);
   const deps=await attachDependencies(root,worktree);events.push(event('inspect',deps?'Reused installed dependencies through isolated worktree.':'No reusable node_modules found; validation may use package-manager cache.'));
   branch=`agent/munin-${new Date().toISOString().slice(0,10).replace(/-/g,'')}-${slug(objective)}-${id.slice(0,4)}`;const sw=await run('git',['switch','-c',branch],worktree,30_000);if(!sw.ok)throw new Error(`branch creation failed: ${sw.stderr}`);
   events.push(event('inspect','Isolated worktree ready.',`${branch} @ ${worktree}`));
   const readPlan=cleanJson<ReadPlan>(await completeWithLlm(plannerSystem,`Objective:\n${objective}\n\nRepository tree:\n${tree.join('\n')}`,1600));events.push(event('plan',readPlan.strategy??'Engineering plan prepared.',(readPlan.filesToRead??[]).join(', ')));
   const context=await readSelected(worktree,readPlan.filesToRead??[]);
   let plan=cleanJson<EditPlan>(await completeWithLlm(editorSystem,`Objective:\n${objective}\n\nRepository tree:\n${tree.join('\n')}\n\nSelected repository files:\n${context}`,7000));
   for(const file of await applyChanges(worktree,plan.changes))changed.add(file);events.push(event('edit',plan.summary??'Files edited.',[...changed].join(', ')));
   let validation=await run(process.platform==='win32'?'npm.cmd':'npm',['test'],worktree,300_000);if(!validation.ok&&!deps&&/not recognized|not found|ENOENT|Cannot find package|Cannot find module/i.test(`${validation.stdout}\n${validation.stderr}`)){const install=await run(process.platform==='win32'?'npm.cmd':'npm',['install'],worktree,300_000);events.push(event('validate',install.ok?'Dependencies installed for isolated validation.':'Dependency install unavailable.',install.stderr.slice(-3000)));if(install.ok)validation=await run(process.platform==='win32'?'npm.cmd':'npm',['test'],worktree,300_000)}events.push(event('validate',validation.ok?'npm test passed.':'npm test failed.',`${validation.stdout}\n${validation.stderr}`.slice(-6000)));
   for(let attempt=1;!validation.ok&&attempt<=2;attempt++){
    const repairContext=await readSelected(worktree,[...changed]);plan=cleanJson<EditPlan>(await completeWithLlm(repairSystem,`Objective:\n${objective}\n\nAttempt: ${attempt}\n\nValidation output:\n${(`${validation.stdout}\n${validation.stderr}`).slice(-10000)}\n\nCurrent changed files:\n${repairContext}`,7000));
    for(const file of await applyChanges(worktree,plan.changes))changed.add(file);events.push(event('repair',`Repair attempt ${attempt} applied.`,[...changed].join(', ')));validation=await run(process.platform==='win32'?'npm.cmd':'npm',['test'],worktree,300_000);events.push(event('validate',validation.ok?'npm test passed.':`npm test still failing after repair ${attempt}.`,`${validation.stdout}\n${validation.stderr}`.slice(-6000)));
   }
   if(!validation.ok)return {status:'failed',objective,branch,worktree,changedFiles:[...changed],events:[...events,event('failed','Validation failed after bounded repair attempts.')],validation:`${validation.stdout}\n${validation.stderr}`.slice(-10000),message:'Build interrompido porque os testes continuam falhando; nenhuma alteração foi mesclada na branch principal.'};
   const status=await run('git',['status','--porcelain'],worktree,20_000);if(!status.stdout.trim())return {status:'completed',objective,branch,worktree,changedFiles:[],events:[...events,event('completed','Objective required no repository changes.')],validation:'npm test passed',delivery:'local-commit',message:'Validação passou; nenhuma alteração de código foi necessária.'};
   await run('git',['add','--all'],worktree,30_000);const commitMessage=`munin: ${(plan.summary??objective).replace(/[\r\n]+/g,' ').slice(0,68)}`;const commit=await run('git',['commit','-m',commitMessage],worktree,60_000);if(!commit.ok)throw new Error(`commit failed: ${commit.stderr}`);const sha=(await run('git',['rev-parse','HEAD'],worktree,20_000)).stdout.trim();events.push(event('commit','Validated engineering change committed.',sha));
   let delivery:'pull-request'|'pushed-branch'|'local-commit'='local-commit';let pullRequest:string|undefined;if(process.env.MUNIN_ENGINEERING_AUTO_PUSH!=='0'){const push=await run('git',['push','-u','origin',branch],worktree,120_000);if(push.ok){delivery='pushed-branch';events.push(event('push','Agent branch pushed to origin.',branch));const gh=await run('gh',['--version'],worktree,15_000);if(gh.ok&&process.env.MUNIN_ENGINEERING_AUTO_PR!=='0'){const pr=await run('gh',['pr','create','--base','main','--head',branch,'--title',commitMessage,'--body',`Autonomous Munin build.\n\nObjective: ${objective}\n\nValidated locally with npm test.`],worktree,60_000);pullRequest=firstUrl(`${pr.stdout}\n${pr.stderr}`);if(pr.ok&&pullRequest){delivery='pull-request';events.push(event('pr','Pull request created.',pullRequest));if(process.env.MUNIN_ENGINEERING_WATCH_CI==='1'){const checks=await run('gh',['pr','checks','--watch','--fail-fast'],worktree,300_000);events.push(event('ci',checks.ok?'GitHub checks passed.':'GitHub checks did not pass within the bounded watch.',`${checks.stdout}\n${checks.stderr}`.slice(-5000)))}}}}else events.push(event('push','Push unavailable; validated commit remains local.',push.stderr.slice(-2000)))}
   events.push(event('completed','Engineering loop completed.'));return {status:'completed',objective,branch,commit:sha,pullRequest,worktree,changedFiles:[...changed],events,validation:'npm test passed',delivery,message:pullRequest?`Build validado e PR criado: ${pullRequest}`:delivery==='pushed-branch'?`Build validado e enviado para ${branch}.`:`Build validado e commitado localmente em ${branch}.`};
  }catch(error){const message=error instanceof Error?error.message:String(error);return {status:'failed',objective,branch:branch||undefined,worktree:worktree||undefined,changedFiles:[...changed],events:[...events,event('failed',message)],message}}
 }
}
