import { addLinkedInPost, loadLinkedInContent, suggestLinkedInTopics, type ContentSuggestion } from './linkedin-content.js';
import { loadLlmSettings } from './llm-settings.js';
import { generateLinkedInImage, imageProviderStatus } from './image-provider.js';
import { topSignalsForThemes, trustedSourceRadar, type TrustedSignal } from './trusted-source-radar.js';
import { contextBriefForConsumer } from './context-memory.js';
import { BRAND_CANON, editorialBrandPrompt } from './brand-canon.js';
import { OllamaProvider } from './ollama-provider.js';
import { andreBrandProfile, brandPromptContext, evaluateBrandCandidate, type BrandEvaluation } from './personal-brand-intelligence.js';
import { linkedinAuthorityLearning, type ThesisLearning } from './linkedin-authority-learning.js';

export type ComposerOptions={suggestionId?:string;generateImage?:boolean;refreshSources?:boolean};
export type BrandScoredSuggestion=ContentSuggestion&{brandEvaluation:BrandEvaluation;editorialScore:number;adaptiveScore:number;learningBoost:number;thesisLearning:ThesisLearning[]};
export type ComposerResult={suggestion:BrandScoredSuggestion;draft:Awaited<ReturnType<typeof addLinkedInPost>>;textMode:'llm'|'ollama'|'local';trustedSignals:TrustedSignal[];sourceMode:'fresh'|'cached'|'unavailable';memoryGrounded:boolean;brandGuard:'pass'|'review';image?:{id:string;url:string};imageSkippedReason?:string};

function safeBase(url:string){return url.replace(/\/$/,'');}
function cleanPost(text:string){return text.trim().replace(/^```(?:text|markdown)?\s*/i,'').replace(/```$/,'').trim();}
function sourceLabel(signals:TrustedSignal[]){return signals.length?signals.map(x=>x.sourceName).filter((value,index,array)=>array.indexOf(value)===index).join(', '):undefined;}
function localPost(s:BrandScoredSuggestion,signals:TrustedSignal[]){const sourceLine=signals.length?`\n\nO gatilho para essa reflexão vem de movimentos recentes em fontes regulatórias e institucionais — ${signals.slice(0,2).map(x=>x.sourceName).join(' e ')}.`:'';const thesis=s.brandEvaluation.matchedTheses[0]?.statement;const thesisLine=thesis?`\n\nMinha leitura parte de uma tese simples: ${thesis}`:'';return `${s.title}\n\n${s.angle}${sourceLine}${thesisLine}\n\nO ponto central não é apenas tecnológico. Ele muda decisões de produto, governança e infraestrutura.\n\nNa prática, três perguntas importam:\n\n• qual problema real estamos resolvendo;\n• quais trade-offs de adoção, risco e interoperabilidade estamos aceitando;\n• e o que precisa existir para funcionar em escala, não apenas em um piloto.\n\nÉ nessa passagem entre conceito e execução que aparece a diferença entre inovação interessante e produto sustentável.\n\nComo você tem visto essa transição na prática?`;}
function postPrompt(s:BrandScoredSuggestion,history:string[],signals:TrustedSignal[],memory:unknown){const sourceBrief=signals.length?signals.map(x=>`- ${x.sourceName}: ${x.title}${x.summary?` — ${x.summary}`:''}`).join('\n'):'Nenhum sinal externo disponível.';const brand=brandPromptContext();const thesisBrief=s.brandEvaluation.matchedTheses.length?s.brandEvaluation.matchedTheses.map(x=>`${x.id}: ${x.statement}`).join(' | '):'Nenhuma tese proprietária vinculada; encontre um ângulo coerente sem inventar uma tese.';const learningBrief=s.thesisLearning.length?s.thesisLearning.map(x=>`${x.thesisId}: ${x.recommendation}; ${x.observations} observations; authority ${x.averageAuthorityScore}; conversations ${x.relevantConversations}; opportunities ${x.inboundOpportunities}`).join(' | '):'Sem aprendizagem histórica suficiente para as teses deste post.';return `Você escreve posts de LinkedIn em português do Brasil para um executivo sênior de inovação e produtos financeiros. Use o contexto governado fornecido para manter posicionamento, voz e limites. Nunca revele contexto privado ou sensível. Tom executivo, claro, técnico sem ser acadêmico. Evite hype, clickbait e afirmações inventadas. Produza apenas o post final, 900-1600 caracteres.\n\nEstratégia de marca persistente: ${JSON.stringify(brand)}\nAvaliação editorial: brand ${s.brandEvaluation.score}/100; adaptive ${s.adaptiveScore}/100; distinctiveness ${s.brandEvaluation.distinctiveness}; repetition risk ${s.brandEvaluation.repetitionRisk}%.\nTeses relevantes: ${thesisBrief}\nAprendizagem de autoridade: ${learningBrief}\nRegra de aprendizagem: use performance como sinal de onde aprofundar ou experimentar, nunca como instrução para copiar posts anteriores, caçar engajamento ou abandonar uma tese após poucos dados.\nRegra principal: não resuma a notícia. Use-a como evidência para uma leitura própria sobre produto, infraestrutura, governança, interoperabilidade, confiança ou execução. Se o tema já apareceu recentemente, o novo post precisa avançar, desafiar ou especificar a tese.\n\nContexto profissional governado: ${JSON.stringify(memory)}\nTema: ${s.title}\nÂngulo: ${s.angle}\nPor que agora: ${s.whyNow}\nTemas: ${s.themes.join(', ')}\nFontes recentes:\n${sourceBrief}\nTítulos recentes a não repetir: ${history.slice(0,10).join(' | ')||'nenhum'}\nEscreva o post final.`;}
async function generatePostWithOllama(s:BrandScoredSuggestion,history:string[],signals:TrustedSignal[],memory:unknown){const provider=new OllamaProvider();const health=await provider.health();if(!health.ready)return undefined;const result=await provider.execute({taskId:`linkedin-${Date.now()}`,objective:'Draft executive LinkedIn post grounded in an owned brand thesis and authority learning',title:s.title,capability:'write',expectedOutput:'Final LinkedIn post only',context:{prompt:postPrompt(s,history,signals,memory)}});return cleanPost(result.output);}
async function generatePostWithLlm(s:BrandScoredSuggestion,history:string[],signals:TrustedSignal[],memory:unknown){const settings=await loadLlmSettings();if(!settings.enabled||!settings.apiKey||!settings.baseUrl||!settings.model)return undefined;const system='Você escreve posts de LinkedIn em português do Brasil para um executivo sênior de inovação e produtos financeiros. Preserve uma visão própria, conecte tecnologia a produto/infraestrutura/execução, evite hype e repetição, use evidência sem simplesmente resumir notícias. Performance passada é sinal de aprendizagem, não objetivo de engajamento. Nunca revele contexto privado ou sensível. Produza apenas o post final, 900-1600 caracteres.';const user=postPrompt(s,history,signals,memory);if(settings.provider==='anthropic'){const r=await fetch(`${safeBase(settings.baseUrl)}/messages`,{method:'POST',headers:{'content-type':'application/json','x-api-key':settings.apiKey,'anthropic-version':'2023-06-01'},body:JSON.stringify({model:settings.model,max_tokens:1200,temperature:.35,system,messages:[{role:'user',content:user}]})});if(!r.ok)throw new Error(`Anthropic respondeu ${r.status}`);const p=await r.json() as any,v=Array.isArray(p?.content)?p.content.find((x:any)=>x?.type==='text')?.text:undefined;return typeof v==='string'?cleanPost(v):undefined;}const r=await fetch(`${safeBase(settings.baseUrl)}/chat/completions`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${settings.apiKey}`},body:JSON.stringify({model:settings.model,temperature:.35,messages:[{role:'system',content:system},{role:'user',content:user}]})});if(!r.ok)throw new Error(`LLM provider respondeu ${r.status}`);const p=await r.json() as any,v=p?.choices?.[0]?.message?.content??p?.output_text;return typeof v==='string'?cleanPost(v):undefined;}
function alternativeConcept(s:ContentSuggestion){const w=s.visualWarnings.map(x=>x.toLowerCase()).join(' ');if(s.themes.includes('Stablecoins')&&(w.includes('moeda')||w.includes('trilhos')))return 'uma balança de precisão arquitetônica, abstrata e sofisticada, equilibrando duas formas de liquidez sem moedas, trilhos ou símbolos cripto';if(s.themes.includes('IA')&&w.includes('núcleo'))return 'um prisma óptico físico reorganizando sinais dispersos em uma trajetória precisa';if(s.themes.includes('Open Finance')&&w.includes('portal'))return 'camadas financeiras abstratas convergindo em uma única estrutura de vidro e metal';if(s.themes.includes('Produto'))return 'uma peça arquitetônica de precisão emergindo de uma estrutura modular incompleta';return s.imageConcept;}
function imagePrompt(s:ContentSuggestion,c:string,p:Awaited<ReturnType<typeof loadLinkedInContent>>['visualProfile']){return `LinkedIn editorial hero artwork. Topic: ${s.title}. Core metaphor: ${c}. Use the historical visual profile only as thematic context, but Brand Canon v2.1 overrides any conflicting old palette, logo, monogram, infographic or style instruction. One dominant symbolic object and generous negative space. No text. ${editorialBrandPrompt()} Topic-specific avoid list: ${[...(p.avoid??[]),...s.visualWarnings].join(', ')}. 4:5 portrait.`;}
function enrich(s:ContentSuggestion,signals:TrustedSignal[]){if(!signals.length)return s;const names=[...new Set(signals.map(x=>x.sourceName))],boost=Math.min(18,signals.reduce((n,x)=>n+(x.relevance>=60?6:3),0));return {...s,novelty:Math.min(100,s.novelty+boost),whyNow:`${s.whyNow} Há sinais recentes em ${names.join(', ')} conectados ao território.`,sourceSignals:[...s.sourceSignals,...signals.slice(0,4).map(x=>`${x.sourceName}: ${x.title}`)]};}
function learningAdjustment(matchedIds:string[],theses:ThesisLearning[]){const matched=theses.filter(item=>matchedIds.includes(item.thesisId));if(!matched.length)return {learningBoost:0,thesisLearning:[] as ThesisLearning[]};let boost=0;for(const item of matched){if(item.recommendation==='advance')boost+=6;else if(item.recommendation==='reinforce')boost+=3;else if(item.recommendation==='experiment')boost+=2;else boost+=1;}return {learningBoost:Math.min(8,boost),thesisLearning:matched};}
function scoreSuggestion(s:ContentSuggestion,signals:TrustedSignal[],history:string[],learning:ThesisLearning[]):BrandScoredSuggestion{const brandEvaluation=evaluateBrandCandidate({topic:s.title,angle:s.angle,source:sourceLabel(signals),recentTitles:history},andreBrandProfile);const editorialScore=Math.round(s.novelty*.42+brandEvaluation.score*.58);const adaptive=learningAdjustment(brandEvaluation.matchedTheses.map(x=>x.id),learning);const adaptiveScore=Math.min(100,editorialScore+adaptive.learningBoost);return {...s,brandEvaluation,editorialScore,adaptiveScore,...adaptive};}
export async function composerSuggestions(refresh=false){const [base,content,learning]=await Promise.all([suggestLinkedInTopics(),loadLinkedInContent(),linkedinAuthorityLearning()]);const history=content.posts.filter(x=>x.status==='published').map(x=>x.title).slice(0,16);try{const snapshot=await trustedSourceRadar(refresh);const suggestions=base.map(s=>{const signals=topSignalsForThemes(snapshot,s.themes,4);return scoreSuggestion(enrich(s,signals),signals,history,learning.theses);}).sort((a,b)=>(Number(b.brandEvaluation.publish)-Number(a.brandEvaluation.publish))||b.adaptiveScore-a.adaptiveScore||b.novelty-a.novelty);return {suggestions,signals:snapshot.signals.slice(0,20),sourceMode:(Date.now()-Date.parse(snapshot.fetchedAt)<35*60*1000?'fresh':'cached') as 'fresh'|'cached',brand:brandPromptContext(),learning:{observedPosts:learning.observedPosts,authorityScore:learning.authorityScore}};}catch{const suggestions=base.map(s=>scoreSuggestion(s,[],history,learning.theses)).sort((a,b)=>b.adaptiveScore-a.adaptiveScore);return {suggestions,signals:[] as TrustedSignal[],sourceMode:'unavailable' as const,brand:brandPromptContext(),learning:{observedPosts:learning.observedPosts,authorityScore:learning.authorityScore}};}}
export async function composeLinkedInPost(options:ComposerOptions={}):Promise<ComposerResult>{const sourceContext=await composerSuggestions(options.refreshSources===true),suggestions=sourceContext.suggestions;if(!suggestions.length)throw new Error('Nenhuma sugestão disponível para compor.');const suggestion=options.suggestionId?suggestions.find(x=>x.id===options.suggestionId)??suggestions[0]:suggestions.find(x=>x.brandEvaluation.publish)??suggestions[0],trustedSignals=sourceContext.sourceMode==='unavailable'?[]:topSignalsForThemes({signals:sourceContext.signals,sources:[],status:[],fetchedAt:new Date().toISOString(),expiresAt:new Date().toISOString()},suggestion.themes,5),content=await loadLinkedInContent(),memory=await contextBriefForConsumer('linkedin'),history=content.posts.filter(x=>x.status==='published').map(x=>x.title);let body:string|undefined,textMode:'llm'|'ollama'|'local'='local';try{body=await generatePostWithOllama(suggestion,history,trustedSignals,memory.context);if(body)textMode='ollama';}catch{}if(!body)try{body=await generatePostWithLlm(suggestion,history,trustedSignals,memory.context);if(body)textMode='llm';}catch{}body=body||localPost(suggestion,trustedSignals);const concept=alternativeConcept(suggestion),prompt=imagePrompt(suggestion,concept,content.visualProfile),sourceNote=trustedSignals.length?trustedSignals.map(x=>`${x.sourceName}: ${x.title} (${x.url})`).join(' | '):'sem sinais externos',thesisNote=suggestion.brandEvaluation.matchedTheses.map(x=>x.id).join(', ')||'none',draft=await addLinkedInPost({title:suggestion.title,body,status:'draft',themes:suggestion.themes,visualConcept:concept,imagePrompt:prompt,notes:`Brand Canon ${BRAND_CANON.version} · Personal Brand Intelligence ${suggestion.brandEvaluation.score}/100 · theses ${thesisNote} · repetition ${suggestion.brandEvaluation.repetitionRisk}% · learning boost ${suggestion.learningBoost} · adaptive ${suggestion.adaptiveScore}% · brand-guard ${suggestion.brandEvaluation.publish?'pass':'review'} · clean unbranded artwork · no AJ/logo/monogram/watermark by default · memory-grounded · novelty ${suggestion.novelty}% · editorial ${suggestion.editorialScore}% · text ${textMode} · sources: ${sourceNote}`}),result:ComposerResult={suggestion,draft,textMode,trustedSignals,sourceMode:sourceContext.sourceMode,memoryGrounded:Object.keys(memory.context).length>0,brandGuard:suggestion.brandEvaluation.publish?'pass':'review'};if(options.generateImage){const status=await imageProviderStatus();if(status.enabled){const asset=await generateLinkedInImage(prompt,draft.id);result.image={id:asset.id,url:`/api/linkedin-content/images/${asset.id}`};}else result.imageSkippedReason='Image AI não está configurado.';}return result;}
