import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { ContextStore } from './store.js';

export type LinkedInPostStatus='published'|'draft'|'idea';
export type LinkedInPost={id:string;title:string;body:string;publishedAt?:string;status:LinkedInPostStatus;themes:string[];visualConcept?:string;imagePrompt?:string;sourceUrl?:string;notes?:string;createdAt:string;updatedAt:string};
export type VisualProfile={name:string;background:string;composition:string;accent:string;style:string;avoid:string[];logoTreatment:string;updatedAt:string};
export type ContentSuggestion={id:string;title:string;angle:string;whyNow:string;novelty:number;themes:string[];sourceSignals:string[];imageConcept:string;imagePrompt:string};
export type LinkedInContentState={posts:LinkedInPost[];visualProfile:VisualProfile;updatedAt:string};

const file=join(process.cwd(),'data','runtime','linkedin-content.json');
const defaultVisual=():VisualProfile=>({
  name:'André Jardim — Premium Editorial',
  background:'fundo grafite/preto minimalista, alto contraste e muito espaço negativo',
  composition:'um único objeto ou símbolo central, composição editorial limpa, sem excesso de elementos',
  accent:'azul elétrico discreto; laranja apenas quando tiver função conceitual clara',
  style:'revista corporativa premium, executivo, tecnológico, sofisticado, realista/cinematográfico, sem aparência de stock photo',
  avoid:['texto dentro da imagem','duas bússolas ou símbolos repetidos','ícones genéricos em excesso','visual neon cyberpunk','carrossel quando um único frame forte funcionar melhor'],
  logoTreatment:'quando usar marca pessoal, preferir monograma AJ sutil, integrado ao objeto e não como selo chamativo',
  updatedAt:new Date().toISOString(),
});
const empty=():LinkedInContentState=>({posts:[],visualProfile:defaultVisual(),updatedAt:new Date(0).toISOString()});
export async function loadLinkedInContent():Promise<LinkedInContentState>{try{const parsed=JSON.parse(await readFile(file,'utf8')) as LinkedInContentState;return {...empty(),...parsed,visualProfile:{...defaultVisual(),...(parsed.visualProfile??{})},posts:Array.isArray(parsed.posts)?parsed.posts:[]};}catch{return empty();}}
async function save(state:LinkedInContentState){state.updatedAt=new Date().toISOString();await mkdir(dirname(file),{recursive:true});await writeFile(file,JSON.stringify(state,null,2),'utf8');return state;}
const id=(prefix:string)=>`${prefix}_${Date.now()}_${Math.random().toString(36).slice(2,8)}`;
function inferThemes(text:string){const t=text.toLowerCase();const map:[string,string[]][]=[['Drex',['drex','real digital']],['Stablecoins',['stablecoin','stablecoins']],['Digital Assets',['digital asset','ativos digitais','tokeniza']],['IA',['inteligência artificial','inteligencia artificial',' ia ','ai ']],['Produto',['produto','product','roadmap','discovery']],['Liderança',['liderança','lideranca','leadership','gestão','gestao']],['Open Finance',['open finance','open banking']],['Pagamentos',['pagamentos','payments','pix']],['Infraestrutura Financeira',['rsfn','infraestrutura financeira','financial infrastructure']],['Identidade Digital',['identidade digital','digital identity']],['Blockchain/DLT',['blockchain','dlt']]];return map.filter(([,keys])=>keys.some(k=>t.includes(k))).map(([name])=>name);}
export async function addLinkedInPost(input:{title:string;body:string;publishedAt?:string;status?:LinkedInPostStatus;themes?:string[];visualConcept?:string;imagePrompt?:string;sourceUrl?:string;notes?:string}){const state=await loadLinkedInContent();const now=new Date().toISOString();const post:LinkedInPost={id:id('li'),title:input.title.trim(),body:input.body.trim(),publishedAt:input.publishedAt,status:input.status??'published',themes:input.themes?.length?input.themes:inferThemes(`${input.title} ${input.body}`),visualConcept:input.visualConcept,imagePrompt:input.imagePrompt,sourceUrl:input.sourceUrl,notes:input.notes,createdAt:now,updatedAt:now};state.posts.unshift(post);await save(state);return post;}
export async function bulkImportLinkedInPosts(items:Omit<Parameters<typeof addLinkedInPost>[0],'status'>[]){const out=[];for(const item of items)out.push(await addLinkedInPost({...item,status:'published'}));return out;}
export async function updateVisualProfile(input:Partial<VisualProfile>){const state=await loadLinkedInContent();state.visualProfile={...state.visualProfile,...input,updatedAt:new Date().toISOString()};await save(state);return state.visualProfile;}
function imagePromptFor(title:string,angle:string,visual:VisualProfile){return `LinkedIn editorial hero image for an executive thought-leadership post. Topic: ${title}. Concept: ${angle}. ${visual.background}. ${visual.composition}. ${visual.accent}. ${visual.style}. No text, no captions, no UI, no generic business people, no duplicated symbols. ${visual.logoTreatment}. 4:5 portrait composition, premium corporate magazine art direction.`;}
function recentThemeCounts(posts:LinkedInPost[]){const counts=new Map<string,number>();posts.filter(p=>p.status==='published').slice(0,12).forEach(p=>p.themes.forEach(t=>counts.set(t,(counts.get(t)??0)+1)));return counts;}
export async function suggestLinkedInTopics():Promise<ContentSuggestion[]>{const content=await loadLinkedInContent();const workspace=await new ContextStore().load();const counts=recentThemeCounts(content.posts);const candidates:{title:string;angle:string;themes:string[];why:string;signals:string[]}[]=[];
const push=(x:typeof candidates[number])=>{if(!candidates.some(c=>c.title===x.title))candidates.push(x)};
for(const r of workspace.research.filter(x=>x.status!=='archived').slice(0,8)){push({title:r.question.replace(/[?]+$/,''),angle:`Transformar a pesquisa em uma visão executiva: o que mudou, por que importa e qual decisão de produto/mercado vem depois.`,themes:inferThemes(r.question),why:'Existe pesquisa ativa no Munin que ainda pode virar conteúdo público.',signals:[`Research: ${r.question}`]});}
for(const p of workspace.projects.filter(x=>x.status==='active').slice(0,8)){if(/linkedin|drex|stable|digital|ai|ia|produto|product|open finance|identidade/i.test(p.name))push({title:p.name,angle:`Extrair uma lição prática do build: menos hype, mais decisão, trade-off e execução.`,themes:inferThemes(p.name),why:'Projeto ativo com material de bastidor suficiente para thought leadership.',signals:[`Project: ${p.name}`]});}
for(const j of workspace.jobs.filter(x=>['applied','interview','offer'].includes(x.status)).slice(0,6)){const t=inferThemes(`${j.company} ${j.role}`);if(t.length)push({title:`O que o mercado está pedindo de líderes de ${t[0]}`,angle:`Usar padrões observáveis nas oportunidades atuais sem falar de processos seletivos específicos: quais competências estão convergindo entre produto, infraestrutura financeira e tecnologia.`,themes:t,why:'O Career OS mostra sinais reais de demanda do mercado.',signals:[`Career signal: ${j.role}`]});}
const evergreen=[
{title:'Quando IA deixa de ser feature e vira sistema operacional de produto',angle:'Diferenciar automação pontual de uma arquitetura de decisão assistida por IA.',themes:['IA','Produto'],why:'Conecta produto, liderança e IA sem repetir um post puramente conceitual.',signals:['Editorial gap']},
{title:'Stablecoins não substituem a infraestrutura financeira — elas pressionam sua evolução',angle:'Mostrar a convivência entre stablecoins, liquidação, compliance, interoperabilidade e infraestrutura regulada.',themes:['Stablecoins','Infraestrutura Financeira','Digital Assets'],why:'Aprofunda digital assets por uma lente de infraestrutura, evitando repetir apenas “stablecoins estão crescendo”.',signals:['Editorial gap']},
{title:'O próximo diferencial em Open Finance não é API: é contexto',angle:'Ir além da conectividade e discutir inteligência, consentimento, identidade e personalização real.',themes:['Open Finance','Identidade Digital','Produto'],why:'Expande Open Finance para produto e experiência.',signals:['Editorial gap']},
{title:'Construir inovação em ambiente regulado é um problema de produto, não de laboratório',angle:'Framework executivo sobre discovery, governança, risco, tecnologia e adoção.',themes:['Produto','Liderança','Infraestrutura Financeira'],why:'Aproxima sua experiência de inovação da linguagem de liderança de produto.',signals:['Editorial gap']}
];evergreen.forEach(push);
return candidates.map((c,i)=>{const repetition=c.themes.reduce((a,t)=>a+(counts.get(t)??0),0);const novelty=Math.max(35,100-repetition*14);const imageConcept=c.themes.includes('Stablecoins')?'uma moeda/objeto translúcido suspenso sobre trilhos de liquidação abstratos':c.themes.includes('IA')?'um núcleo mecânico/minimalista transformando sinais dispersos em uma única trajetória luminosa':c.themes.includes('Open Finance')?'um portal/anel único conectando camadas financeiras sem ícones de bancos':c.themes.includes('Produto')?'um objeto arquitetônico modular com uma peça central em foco':'um único objeto simbólico abstrato ligado ao tema';return {id:`sug_${i}`,title:c.title,angle:c.angle,whyNow:c.why,novelty,themes:c.themes,sourceSignals:c.signals,imageConcept,imagePrompt:imagePromptFor(c.title,imageConcept,content.visualProfile)};}).sort((a,b)=>b.novelty-a.novelty).slice(0,10);}
export async function createPostDraft(input:{title:string;angle:string;themes?:string[]}){const content=await loadLinkedInContent();const themes=input.themes?.length?input.themes:inferThemes(`${input.title} ${input.angle}`);const body=`${input.title}\n\n${input.angle}\n\nEstrutura sugerida:\n1. Abra com uma tese clara — sem “o futuro de...”.\n2. Mostre a tensão ou trade-off real.\n3. Traga 2–3 implicações práticas para produto/mercado.\n4. Feche com uma pergunta específica que convide debate qualificado.`;const visualConcept=themes.includes('Stablecoins')?'um objeto monetário translúcido atravessando uma infraestrutura de liquidação abstrata':themes.includes('IA')?'um núcleo inteligente central organizando sinais complexos em uma direção única':'um objeto simbólico único traduzindo a tese do post';return addLinkedInPost({title:input.title,body,status:'draft',themes,visualConcept,imagePrompt:imagePromptFor(input.title,visualConcept,content.visualProfile),notes:'Draft criado pelo LinkedIn Content Intelligence; refinar texto antes de publicar.'});}
