import { readFile } from 'node:fs/promises';
import { runtimePath } from './config.js';
import { writeJsonAtomic } from './storage.js';
import { loadLinkedInContent } from './linkedin-content.js';
import { andreBrandProfile, evaluateBrandCandidate, type BrandEvaluation } from './personal-brand-intelligence.js';

export type PublisherStatus='draft'|'approved'|'scheduled'|'published'|'revoked';
export interface PublisherRecord{postId:string;status:PublisherStatus;approvedAt?:string;scheduledFor?:string;scheduledAt?:string;revokedAt?:string;publishedAt?:string;publishedUrl?:string;note?:string;updatedAt:string}
export interface PublisherBrandPreflight{evaluation:BrandEvaluation;gate:'pass'|'review';humanOverrideAllowed:true;autonomousPublishAllowed:false}
export interface PublisherPackage{postId:string;title:string;body:string;themes:string[];imagePrompt?:string;visualConcept?:string;status:PublisherStatus;approvedAt?:string;scheduledFor?:string;publicationBoundary:'manual-only';brandPreflight:PublisherBrandPreflight}
interface PublisherState{records:PublisherRecord[];updatedAt:string}

const file=()=>runtimePath('linkedin-publisher.json');
const empty=():PublisherState=>({records:[],updatedAt:new Date(0).toISOString()});
async function loadState():Promise<PublisherState>{try{const parsed=JSON.parse(await readFile(file(),'utf8')) as PublisherState;return {...empty(),...parsed,records:Array.isArray(parsed.records)?parsed.records:[]};}catch{return empty();}}
async function saveState(state:PublisherState){state.updatedAt=new Date().toISOString();await writeJsonAtomic(file(),state);return state;}
function now(){return new Date().toISOString();}
function recordFor(state:PublisherState,postId:string){let record=state.records.find(item=>item.postId===postId);if(!record){record={postId,status:'draft',updatedAt:now()};state.records.push(record);}return record;}
async function assertPost(postId:string){const content=await loadLinkedInContent();const post=content.posts.find(item=>item.id===postId);if(!post)throw new Error('LinkedIn post not found');return post;}
async function syncEditorialHistory(postId:string,publishedAt:string,publishedUrl:string){const content=await loadLinkedInContent();const post=content.posts.find(item=>item.id===postId);if(!post)throw new Error('LinkedIn post not found while synchronizing editorial history');post.status='published';post.publishedAt=publishedAt;post.sourceUrl=publishedUrl;post.updatedAt=publishedAt;content.updatedAt=publishedAt;await writeJsonAtomic(runtimePath('linkedin-content.json'),content);}

export async function publisherBrandPreflight(postId:string):Promise<PublisherBrandPreflight>{const content=await loadLinkedInContent();const post=content.posts.find(item=>item.id===postId);if(!post)throw new Error('LinkedIn post not found');const recentTitles=content.posts.filter(item=>item.status==='published'&&item.id!==postId).map(item=>item.title).slice(0,16);const source=post.sourceUrl||(/sources?:\s*(.+)$/i.exec(post.notes??'')?.[1]);const evaluation=evaluateBrandCandidate({topic:post.title,angle:post.body,source,recentTitles},andreBrandProfile);return {evaluation,gate:evaluation.publish?'pass':'review',humanOverrideAllowed:true,autonomousPublishAllowed:false};}

export async function publisherQueue(){const [content,state]=await Promise.all([loadLinkedInContent(),loadState()]);const byId=new Map(state.records.map(item=>[item.postId,item]));return content.posts.filter(post=>post.status!=='published'||byId.has(post.id)).map(post=>{const record=byId.get(post.id);return {postId:post.id,title:post.title,status:record?.status??(post.status==='published'?'published':'draft'),approvedAt:record?.approvedAt,scheduledFor:record?.scheduledFor,publishedAt:record?.publishedAt??post.publishedAt,publishedUrl:record?.publishedUrl??post.sourceUrl,themes:post.themes,updatedAt:record?.updatedAt??post.updatedAt};}).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));}

export async function approveForPublication(postId:string,note?:string):Promise<PublisherRecord>{await assertPost(postId);const preflight=await publisherBrandPreflight(postId);const state=await loadState();const record=recordFor(state,postId);record.status='approved';record.approvedAt=now();record.revokedAt=undefined;record.scheduledFor=undefined;record.scheduledAt=undefined;const brandNote=`brand-gate:${preflight.gate}; brand-score:${preflight.evaluation.score}; theses:${preflight.evaluation.matchedTheses.map(item=>item.id).join(',')||'none'}`;record.note=[note?.trim(),brandNote].filter(Boolean).join(' | ');record.updatedAt=now();await saveState(state);return record;}
export async function revokePublicationApproval(postId:string,note?:string):Promise<PublisherRecord>{await assertPost(postId);const state=await loadState();const record=recordFor(state,postId);record.status='revoked';record.revokedAt=now();record.scheduledFor=undefined;record.scheduledAt=undefined;record.note=note?.trim()||record.note;record.updatedAt=now();await saveState(state);return record;}
export async function schedulePublication(postId:string,input:{scheduledFor:string;confirmation:string;note?:string}):Promise<PublisherRecord>{await assertPost(postId);if(input.confirmation!=='LINKEDIN_SCHEDULED_MANUALLY')throw new Error('Manual LinkedIn scheduling confirmation is required');const scheduledFor=new Date(input.scheduledFor);if(!Number.isFinite(scheduledFor.getTime()))throw new Error('A valid publication schedule is required');if(scheduledFor.getTime()<=Date.now())throw new Error('Publication schedule must be in the future');const state=await loadState();const record=recordFor(state,postId);if(record.status!=='approved')throw new Error('Post must be approved before it can be scheduled');record.status='scheduled';record.scheduledFor=scheduledFor.toISOString();record.scheduledAt=now();record.note=input.note?.trim()||record.note;record.updatedAt=now();await saveState(state);return record;}
export async function publicationPackage(postId:string):Promise<PublisherPackage>{const [post,state,brandPreflight]=await Promise.all([assertPost(postId),loadState(),publisherBrandPreflight(postId)]);const record=recordFor(state,postId);if(!['approved','scheduled'].includes(record.status))throw new Error('Explicit approval is required before preparing a publication package');return {postId,title:post.title,body:post.body,themes:post.themes,imagePrompt:post.imagePrompt,visualConcept:post.visualConcept,status:record.status,approvedAt:record.approvedAt,scheduledFor:record.scheduledFor,publicationBoundary:'manual-only',brandPreflight};}
export async function markManuallyPublished(postId:string,input:{url:string;confirmation:string;note?:string}):Promise<PublisherRecord>{await assertPost(postId);if(input.confirmation!=='I_PUBLISHED_THIS_MANUALLY')throw new Error('Manual publication confirmation is required');let parsed:URL;try{parsed=new URL(input.url);}catch{throw new Error('A valid published URL is required');}if(!/^https?:$/.test(parsed.protocol))throw new Error('Published URL must use http or https');const state=await loadState();const record=recordFor(state,postId);if(!['approved','scheduled'].includes(record.status))throw new Error('Post must be approved or scheduled before it can be marked published');const publishedAt=now();record.status='published';record.publishedAt=publishedAt;record.publishedUrl=parsed.toString();record.note=input.note?.trim()||record.note;record.updatedAt=publishedAt;await saveState(state);await syncEditorialHistory(postId,publishedAt,record.publishedUrl);return record;}

export function publisherPolicy(){return {externalWriteAllowed:false,publicationBoundary:'manual-only' as const,approvalRequired:true,brandPreflight:true,humanOverrideAllowed:true,autonomousPublishAllowed:false,scheduleSupported:true,scheduleConfirmation:'LINKEDIN_SCHEDULED_MANUALLY',confirmation:'I_PUBLISHED_THIS_MANUALLY'};}
