import { addLinkedInPost, loadLinkedInContent, suggestLinkedInTopics, type ContentSuggestion } from './linkedin-content.js';
import { loadLlmSettings } from './llm-settings.js';
import { generateLinkedInImage, imageProviderStatus } from './image-provider.js';
import { topSignalsForThemes, trustedSourceRadar, type TrustedSignal } from './trusted-source-radar.js';

export type ComposerOptions={suggestionId?:string;generateImage?:boolean;refreshSources?:boolean};
export type ComposerResult={suggestion:ContentSuggestion;draft:Awaited<ReturnType<typeof addLinkedInPost>>;textMode:'llm'|'local';trustedSignals:TrustedSignal[];sourceMode:'fresh'|'cached'|'unavailable';image?:{id:string;url:string};imageSkippedReason?:string};

function safeBase(url:string){return url.replace(/\/$/,'');}
function cleanPost(text:string){return text.trim().replace(/^```(?:text|markdown)?\s*/i,'').replace(/```$/,'').trim();}
function localPost(s:ContentSuggestion,signals:TrustedSignal[]){const sourceLine=signals.length?`\n\nO gatilho para essa reflexão vem de movimentos recentes em fontes regulatórias e institucionais — ${signals.slice(0,2).map(x=>x.sourceName).join(' e ')} — que reforçam que o tema já está saindo do plano conceitual.`:'';return `${s.title}\n\n${s.angle}${sourceLine}\n\nO ponto que considero mais relevante é que essa discussão não é apenas tecnológica. Ela muda decisões de produto, governança e infraestrutura.\n\nNa prática, três perguntas importam:\n\n• qual problema real estamos resolvendo;\n• quais trade-offs de adoção, risco e interoperabilidade estamos aceitando;\n• e o que precisa existir para a solução funcionar em escala, não apenas em um piloto.\n\nÉ nessa passagem entre conceito e execução que normalmente aparece a diferença entre inovação interessante e produto sustentável.\n\nComo você tem visto essa transição na prática?`;}

async function generatePostWithLlm(s:ContentSuggestion,history:string[],signals:TrustedSignal[]){const settings=await loadLlmSettings();if(!settings.enabled||!settings.apiKey||!settings.baseUrl||!settings.model)return undefined;
  const system='Você escreve posts de LinkedIn em português do Brasil para um executivo sênior de inovação e produtos financeiros. Tom: executivo, claro, técnico sem ser acadêmico, assertivo sem arrogância. Evite frases genéricas de IA, hype, emojis em excesso, títulos clickbait e listas longas. O post deve soar como experiência prática de quem trabalhou com infraestrutura financeira, inovação, Open Finance, ativos digitais, IA e produto. Produza apenas o texto final do post, entre 900 e 1600 caracteres, com abertura forte, desenvolvimento em parágrafos curtos, 2 ou 3 implicações práticas e fechamento que convide debate qualificado. Não invente números, datas, normas ou experiências. Quando houver fontes confiáveis no briefing, use somente o que está explicitamente nos títulos/resumos fornecidos e não atribua conclusões que a fonte não afirmou.';
  const sourceBrief=signals.length?signals.map(x=>`- ${x.sourceName}: ${x.title}${x.summary?` — ${x.summary}`:''}`).join('\n'):'Nenhum sinal externo disponível; não alegue acontecimentos recentes.';
  const user=`Tema: ${s.title}\nÂngulo: ${s.angle}\nPor que agora: ${s.whyNow}\nTemas: ${s.themes.join(', ')}\nSinais internos: ${s.sourceSignals.join(' | ')}\nFontes confiáveis recentes:\n${sourceBrief}\nTítulos recentes a não repetir: ${history.slice(0,8).join(' | ') || 'nenhum'}\nEscreva o post final.`;
  if(settings.provider==='anthropic'){
    const r=await fetch(`${safeBase(settings.baseUrl)}/messages`,{method:'POST',headers:{'content-type':'application/json','x-api-key':settings.apiKey,'anthropic-version':'2023-06-01'},body:JSON.stringify({model:settings.model,max_tokens:1200,temperature:0.4,system,messages:[{role:'user',content:user}]})});
    if(!r.ok)throw new Error(`Anthropic respondeu ${r.status}`);const payload=await r.json() as any;const value=Array.isArray(payload?.content)?payload.content.find((x:any)=>x?.type==='text')?.text:undefined;return typeof value==='string'?cleanPost(value):undefined;
  }
  const r=await fetch(`${safeBase(settings.baseUrl)}/chat/completions`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${settings.apiKey}`},body:JSON.stringify({model:settings.model,temperature:0.4,messages:[{role:'system',content:system},{role:'user',content:user}]})});
  if(!r.ok)throw new Error(`LLM provider respondeu ${r.status}`);const payload=await r.json() as any;const value=payload?.choices?.[0]?.message?.content??payload?.output_text;return typeof value==='string'?cleanPost(value):undefined;
}

function alternativeConcept(s:ContentSuggestion){const warned=s.visualWarnings.map(x=>x.toLowerCase()).join(' ');if(s.themes.includes('Stablecoins')&&(warned.includes('moeda')||warned.includes('trilhos')))return 'uma balança de precisão arquitetônica, abstrata e sofisticada, equilibrando duas formas de liquidez sem moedas, sem trilhos e sem símbolos cripto';if(s.themes.includes('IA')&&warned.includes('núcleo'))return 'um prisma óptico único reorganizando sinais dispersos em uma trajetória precisa, sem cérebro, robô ou núcleo mecânico';if(s.themes.includes('Open Finance')&&warned.includes('portal'))return 'camadas financeiras abstratas convergindo em uma lente de vidro única, sem portal, anel ou logos bancários';if(s.themes.includes('Produto'))return 'uma peça arquitetônica de precisão emergindo de uma malha modular incompleta, com um único ponto focal';return s.imageConcept;}
function imagePrompt(s:ContentSuggestion,concept:string,profile:Awaited<ReturnType<typeof loadLinkedInContent>>['visualProfile']){const avoid=[...(profile.avoid??[]),...s.visualWarnings].join(', ');return `LinkedIn editorial hero image for executive thought leadership. Topic: ${s.title}. Core visual concept: ${concept}. ${profile.background}. ${profile.composition}. ${profile.accent}. ${profile.style}. Preserve a premium corporate magazine aesthetic with one dominant symbolic object and generous negative space. Avoid: ${avoid}. No text, captions, UI, logos, generic business people, crypto clichés or duplicated symbols. ${profile.logoTreatment}. 4:5 portrait composition.`;}
function enrichWithTrustedSources(s:ContentSuggestion,signals:TrustedSignal[]){if(!signals.length)return s;const names=[...new Set(signals.map(x=>x.sourceName))];const sourceSignals=[...s.sourceSignals,...signals.slice(0,4).map(x=>`${x.sourceName}: ${x.title}`)];const boost=Math.min(18,signals.reduce((sum,x)=>sum+(x.relevance>=60?6:3),0));return {...s,novelty:Math.min(100,s.novelty+boost),whyNow:`${s.whyNow} Há sinais recentes em ${names.join(', ')} conectados diretamente a este território.`,sourceSignals};}

export async function composerSuggestions(refreshSources=false){const base=await suggestLinkedInTopics();let snapshot;try{snapshot=await trustedSourceRadar(refreshSources);}catch{return {suggestions:base,signals:[] as TrustedSignal[],sourceMode:'unavailable' as const};}const enriched=base.map(s=>enrichWithTrustedSources(s,topSignalsForThemes(snapshot,s.themes,4))).sort((a,b)=>b.novelty-a.novelty);return {suggestions:enriched,signals:snapshot.signals.slice(0,20),sourceMode:(Date.now()-Date.parse(snapshot.fetchedAt)<35*60*1000?'fresh':'cached') as 'fresh'|'cached'};}

export async function composeLinkedInPost(options:ComposerOptions={}):Promise<ComposerResult>{const sourceContext=await composerSuggestions(options.refreshSources===true);const suggestions=sourceContext.suggestions;if(!suggestions.length)throw new Error('Nenhuma sugestão disponível para compor.');const suggestion=options.suggestionId?suggestions.find(x=>x.id===options.suggestionId)??suggestions[0]:suggestions[0];const trustedSignals=sourceContext.sourceMode==='unavailable'?[]:topSignalsForThemes({signals:sourceContext.signals,sources:[],status:[],fetchedAt:new Date().toISOString(),expiresAt:new Date().toISOString()},suggestion.themes,5);const content=await loadLinkedInContent();let body:string|undefined;let textMode:'llm'|'local'='local';try{body=await generatePostWithLlm(suggestion,content.posts.filter(x=>x.status==='published').map(x=>x.title),trustedSignals);if(body)textMode='llm';}catch{body=undefined;}body=body||localPost(suggestion,trustedSignals);const concept=alternativeConcept(suggestion);const prompt=imagePrompt(suggestion,concept,content.visualProfile);const sourceNote=trustedSignals.length?trustedSignals.map(x=>`${x.sourceName}: ${x.title} (${x.url})`).join(' | '):'sem sinais externos';const draft=await addLinkedInPost({title:suggestion.title,body,status:'draft',themes:suggestion.themes,visualConcept:concept,imagePrompt:prompt,notes:`M15.7 trusted-source composer · editorial novelty ${suggestion.novelty}% · visual novelty ${suggestion.visualNovelty}% · text ${textMode} · sources: ${sourceNote}`});const result:ComposerResult={suggestion,draft,textMode,trustedSignals,sourceMode:sourceContext.sourceMode};if(options.generateImage){const status=await imageProviderStatus();if(status.enabled){const asset=await generateLinkedInImage(prompt,draft.id);result.image={id:asset.id,url:`/api/linkedin-content/images/${asset.id}`};}else result.imageSkippedReason='Image AI não está configurado.';}return result;}
