import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, extname, join } from 'node:path';
import { ContextStore } from './store.js';

export type LinkedInPostStatus='published'|'draft'|'idea';
export type VisualSignature={objects:string[];composition:string;motifs:string[]};
export type LinkedInPost={id:string;title:string;body:string;publishedAt?:string;status:LinkedInPostStatus;themes:string[];visualConcept?:string;imagePrompt?:string;sourceUrl?:string;notes?:string;visualSignature?:VisualSignature;visualReferenceId?:string;createdAt:string;updatedAt:string};
export type VisualReference={id:string;postId?:string;label:string;sourcePath?:string;mimeType?:string;objects:string[];composition:string;motifs:string[];notes?:string;createdAt:string};
export type VisualProfile={name:string;background:string;composition:string;accent:string;style:string;avoid:string[];logoTreatment:string;updatedAt:string};
export type ContentSuggestion={id:string;title:string;angle:string;whyNow:string;novelty:number;themes:string[];sourceSignals:string[];imageConcept:string;imagePrompt:string;visualNovelty:number;visualWarnings:string[]};
export type LinkedInContentState={posts:LinkedInPost[];visualReferences:VisualReference[];visualProfile:VisualProfile;updatedAt:string};

const file=join(process.cwd(),'data','runtime','linkedin-content.json');
const historyImageDir=join(process.cwd(),'data','runtime','linkedin-history-images');
const defaultVisual=():VisualProfile=>({name:'André Jardim — Premium Editorial',background:'fundo grafite/preto minimalista, alto contraste e muito espaço negativo',composition:'um único objeto ou símbolo central, composição editorial limpa, sem excesso de elementos',accent:'azul elétrico discreto; laranja apenas quando tiver função conceitual clara',style:'revista corporativa premium, executivo, tecnológico, sofisticado, realista/cinematográfico, sem aparência de stock photo',avoid:['texto dentro da imagem','duas bússolas ou símbolos repetidos','ícones genéricos em excesso','visual neon cyberpunk','carrossel quando um único frame forte funcionar melhor'],logoTreatment:'quando usar marca pessoal, preferir monograma AJ sutil, integrado ao objeto e não como selo chamativo',updatedAt:new Date().toISOString()});
const empty=():LinkedInContentState=>({posts:[],visualReferences:[],visualProfile:defaultVisual(),updatedAt:new Date(0).toISOString()});
export async function loadLinkedInContent():Promise<LinkedInContentState>{try{const parsed=JSON.parse(await readFile(file,'utf8')) as Partial<LinkedInContentState>;return {...empty(),...parsed,visualProfile:{...defaultVisual(),...(parsed.visualProfile??{})},posts:Array.isArray(parsed.posts)?parsed.posts:[],visualReferences:Array.isArray(parsed.visualReferences)?parsed.visualReferences:[]};}catch{return empty();}}
async function save(state:LinkedInContentState){state.updatedAt=new Date().toISOString();await mkdir(dirname(file),{recursive:true});await writeFile(file,JSON.stringify(state,null,2),'utf8');return state;}
const id=(prefix:string)=>`${prefix}_${Date.now()}_${Math.random().toString(36).slice(2,8)}`;
function uniq(values:string[]){return [...new Set(values.map(x=>x.trim()).filter(Boolean))];}
function inferThemes(text:string){const t=` ${text.toLowerCase()} `;const map:[string,string[]][]=[['Drex',['drex','real digital']],['Stablecoins',['stablecoin']],['Digital Assets',['digital asset','ativos digitais','tokeniza']],['IA',['inteligência artificial','inteligencia artificial',' ia ',' ai ']],['Produto',['produto','product','roadmap','discovery']],['Liderança',['liderança','lideranca','leadership','gestão','gestao']],['Open Finance',['open finance','open banking']],['Pagamentos',['pagamentos','payments','pix']],['Infraestrutura Financeira',['rsfn','infraestrutura financeira','financial infrastructure']],['Identidade Digital',['identidade digital','digital identity']],['Blockchain/DLT',['blockchain','dlt']]];return map.filter(([,keys])=>keys.some(k=>t.includes(k))).map(([name])=>name);}
function inferVisualSignature(text:string):VisualSignature{const t=text.toLowerCase();const candidates:[string,string[]][]=[['bússola',['bússola','compass']],['moeda',['moeda','coin','stablecoin']],['anel/portal',['anel','portal','ring']],['núcleo',['núcleo','nucleo','core']],['trilhos',['trilho','rail']],['ponte',['ponte','bridge']],['bloco/cubo',['cubo','cube','bloco']],['rede',['rede','network']],['engrenagem',['engrenagem','gear']],['chave',['chave','key']],['escudo',['escudo','shield']],['farol',['farol','lighthouse']],['árvore',['árvore','tree']],['monograma AJ',['monograma aj',' aj ']]];const objects=candidates.filter(([,keys])=>keys.some(k=>t.includes(k))).map(([name])=>name);const motifs=uniq([t.includes('translúc')||t.includes('transluc')?'translúcido':'',t.includes('suspens')?'suspenso':'',t.includes('luminos')||t.includes('glow')?'luz focal':'',t.includes('metal')?'metálico':'',t.includes('glass')||t.includes('vidro')?'vidro':'',t.includes('blue')||t.includes('azul')?'azul':'']);const composition=t.includes('central')?'objeto central':t.includes('simétr')?'simétrica':t.includes('isométr')?'isométrica':'editorial minimalista';return {objects:objects.length?objects:['objeto abstrato'],composition,motifs};}
export async function addLinkedInPost(input:{title:string;body:string;publishedAt?:string;status?:LinkedInPostStatus;themes?:string[];visualConcept?:string;imagePrompt?:string;sourceUrl?:string;notes?:string;visualSignature?:VisualSignature;visualReferenceId?:string}){const state=await loadLinkedInContent();const now=new Date().toISOString();const signature=input.visualSignature??inferVisualSignature(`${input.visualConcept??''} ${input.imagePrompt??''}`);const post:LinkedInPost={id:id('li'),title:input.title.trim(),body:input.body.trim(),publishedAt:input.publishedAt,status:input.status??'published',themes:input.themes?.length?uniq(input.themes):inferThemes(`${input.title} ${input.body}`),visualConcept:input.visualConcept,imagePrompt:input.imagePrompt,sourceUrl:input.sourceUrl,notes:input.notes,visualSignature:signature,visualReferenceId:input.visualReferenceId,createdAt:now,updatedAt:now};state.posts.unshift(post);await save(state);return post;}
export async function bulkImportLinkedInPosts(items:{title:string;body:string;publishedAt?:string;themes?:string[];visualConcept?:string;imagePrompt?:string;sourceUrl?:string;notes?:string}[]){const state=await loadLinkedInContent();let added=0,duplicates=0;const imported:LinkedInPost[]=[];for(const item of items.slice(0,200)){const key=`${item.title.trim().toLowerCase()}|${item.publishedAt??''}`;if(state.posts.some(p=>`${p.title.trim().toLowerCase()}|${p.publishedAt??''}`===key)){duplicates++;continue;}const now=new Date().toISOString();const post:LinkedInPost={id:id('li'),title:item.title.trim(),body:item.body.trim(),publishedAt:item.publishedAt,status:'published',themes:item.themes?.length?uniq(item.themes):inferThemes(`${item.title} ${item.body}`),visualConcept:item.visualConcept,imagePrompt:item.imagePrompt,sourceUrl:item.sourceUrl,notes:item.notes,visualSignature:inferVisualSignature(`${item.visualConcept??''} ${item.imagePrompt??''}`),createdAt:now,updatedAt:now};state.posts.push(post);imported.push(post);added++;}state.posts.sort((a,b)=>(b.publishedAt??b.createdAt).localeCompare(a.publishedAt??a.createdAt));await save(state);return {added,duplicates,imported};}
export async function addVisualReference(input:{label:string;postId?:string;sourcePath?:string;mimeType?:string;objects?:string[];composition?:string;motifs?:string[];notes?:string;dataBase64?:string}){const state=await loadLinkedInContent();let sourcePath=input.sourcePath;let mimeType=input.mimeType;if(input.dataBase64){const match=input.dataBase64.match(/^data:(image\/(?:png|jpeg|webp));base64,(.+)$/);if(!match)throw new Error('Imagem deve ser PNG, JPEG ou WEBP.');const bytes=Buffer.from(match[2],'base64');if(bytes.length>4_000_000)throw new Error('Imagem de referência deve ter no máximo 4 MB.');const ext=match[1]==='image/jpeg'?'.jpg':match[1]==='image/webp'?'.webp':'.png';await mkdir(historyImageDir,{recursive:true});const name=`ref_${Date.now()}_${Math.random().toString(36).slice(2,7)}${ext}`;sourcePath=join(historyImageDir,name);await writeFile(sourcePath,bytes);mimeType=match[1];}
const inferred=inferVisualSignature(`${input.label} ${input.notes??''}`);const ref:VisualReference={id:id('vref'),postId:input.postId,label:input.label.trim(),sourcePath,mimeType,objects:input.objects?.length?uniq(input.objects):inferred.objects,composition:input.composition?.trim()||inferred.composition,motifs:input.motifs?.length?uniq(input.motifs):inferred.motifs,notes:input.notes,createdAt:new Date().toISOString()};state.visualReferences.unshift(ref);if(input.postId){const post=state.posts.find(p=>p.id===input.postId);if(post){post.visualReferenceId=ref.id;post.visualSignature={objects:ref.objects,composition:ref.composition,motifs:ref.motifs};post.updatedAt=new Date().toISOString();}}await save(state);return ref;}
export async function updateVisualProfile(input:Partial<VisualProfile>){const state=await loadLinkedInContent();state.visualProfile={...state.visualProfile,...input,updatedAt:new Date().toISOString()};await save(state);return state.visualProfile;}
function imagePromptFor(title:string,angle:string,visual:VisualProfile,warnings:string[]=[]){const avoidHistory=warnings.length?`Avoid repeating these previously used visual territories: ${warnings.join(', ')}.`:'';return `LinkedIn editorial hero image for an executive thought-leadership post. Topic: ${title}. Concept: ${angle}. ${visual.background}. ${visual.composition}. ${visual.accent}. ${visual.style}. No text, no captions, no UI, no generic business people, no duplicated symbols. ${avoidHistory} ${visual.logoTreatment}. 4:5 portrait composition, premium corporate magazine art direction.`;}
function recentThemeCounts(posts:LinkedInPost[]){const counts=new Map<string,number>();posts.filter(p=>p.status==='published').slice(0,12).forEach(p=>p.themes.forEach(t=>counts.set(t,(counts.get(t)??0)+1)));return counts;}
function visualCounts(content:LinkedInContentState){const counts=new Map<string,number>();for(const p of content.posts.filter(x=>x.status==='published').slice(0,16)){for(const o of p.visualSignature?.objects??[])counts.set(o,(counts.get(o)??0)+1);}for(const r of content.visualReferences.slice(0,20)){for(const o of r.objects)counts.set(o,(counts.get(o)??0)+1);}return counts;}
function conceptFor(themes:string[]){if(themes.includes('Stablecoins'))return 'uma moeda/objeto translúcido suspenso sobre trilhos de liquidação abstratos';if(themes.includes('IA'))return 'um núcleo mecânico minimalista transformando sinais dispersos em uma única trajetória luminosa';if(themes.includes('Open Finance'))return 'um portal único conectando camadas financeiras sem ícones de bancos';if(themes.includes('Produto'))return 'um objeto arquitetônico modular com uma peça central em foco';return 'um único objeto simbólico abstrato ligado ao tema';}
export async function suggestLinkedInTopics():Promise<ContentSuggestion[]>{const content=await loadLinkedInContent();const workspace=await new ContextStore().load();const counts=recentThemeCounts(content.posts);const usedVisuals=visualCounts(content);const candidates:{title:string;angle:string;themes:string[];why:string;signals:string[]}[]=[];const push=(x:typeof candidates[number])=>{if(!candidates.some(c=>c.title===x.title))candidates.push(x)};
for(const r of workspace.research.filter(x=>x.status!=='archived').slice(0,8))push({title:r.question.replace(/[?]+$/,''),angle:'Transformar a pesquisa em uma visão executiva: o que mudou, por que importa e qual decisão de produto/mercado vem depois.',themes:inferThemes(r.question),why:'Existe pesquisa ativa no Munin que ainda pode virar conteúdo público.',signals:[`Research: ${r.question}`]});
for(const p of workspace.projects.filter(x=>x.status==='active').slice(0,8)){if(/linkedin|drex|stable|digital|ai|ia|produto|product|open finance|identidade/i.test(p.name))push({title:p.name,angle:'Extrair uma lição prática do build: menos hype, mais decisão, trade-off e execução.',themes:inferThemes(p.name),why:'Projeto ativo com material de bastidor suficiente para thought leadership.',signals:[`Project: ${p.name}`]});}
for(const j of workspace.jobs.filter(x=>['applied','interview','offer'].includes(x.status)).slice(0,6)){const t=inferThemes(`${j.company} ${j.role}`);if(t.length)push({title:`O que o mercado está pedindo de líderes de ${t[0]}`,angle:'Usar padrões observáveis nas oportunidades atuais sem falar de processos seletivos específicos: competências que convergem entre produto, infraestrutura financeira e tecnologia.',themes:t,why:'O Career OS mostra sinais reais de demanda do mercado.',signals:[`Career signal: ${j.role}`]});}
[
{title:'Quando IA deixa de ser feature e vira sistema operacional de produto',angle:'Diferenciar automação pontual de uma arquitetura de decisão assistida por IA.',themes:['IA','Produto'],why:'Conecta produto, liderança e IA sem repetir um post puramente conceitual.',signals:['Editorial gap']},
{title:'Stablecoins não substituem a infraestrutura financeira — elas pressionam sua evolução',angle:'Mostrar a convivência entre stablecoins, liquidação, compliance, interoperabilidade e infraestrutura regulada.',themes:['Stablecoins','Infraestrutura Financeira','Digital Assets'],why:'Aprofunda digital assets por uma lente de infraestrutura.',signals:['Editorial gap']},
{title:'O próximo diferencial em Open Finance não é API: é contexto',angle:'Ir além da conectividade e discutir inteligência, consentimento, identidade e personalização real.',themes:['Open Finance','Identidade Digital','Produto'],why:'Expande Open Finance para produto e experiência.',signals:['Editorial gap']},
{title:'Construir inovação em ambiente regulado é um problema de produto, não de laboratório',angle:'Framework executivo sobre discovery, governança, risco, tecnologia e adoção.',themes:['Produto','Liderança','Infraestrutura Financeira'],why:'Aproxima inovação da linguagem de liderança de produto.',signals:['Editorial gap']}
].forEach(push);
return candidates.map((c,i)=>{const themeRepetition=c.themes.reduce((a,t)=>a+(counts.get(t)??0),0);const imageConcept=conceptFor(c.themes);const signature=inferVisualSignature(imageConcept);const visualRepetition=signature.objects.reduce((a,o)=>a+(usedVisuals.get(o)??0),0);const novelty=Math.max(30,100-themeRepetition*12-visualRepetition*5);const visualNovelty=Math.max(20,100-visualRepetition*18);const visualWarnings=signature.objects.filter(o=>(usedVisuals.get(o)??0)>0).map(o=>`${o} (${usedVisuals.get(o)} usos)`);return {id:`sug_${i}`,title:c.title,angle:c.angle,whyNow:c.why,novelty,themes:c.themes,sourceSignals:c.signals,imageConcept,imagePrompt:imagePromptFor(c.title,imageConcept,content.visualProfile,visualWarnings),visualNovelty,visualWarnings};}).sort((a,b)=>b.novelty-a.novelty).slice(0,10);}
export async function editorialHistoryAnalysis(){const content=await loadLinkedInContent();const theme=new Map<string,number>();const objects=new Map<string,number>();const compositions=new Map<string,number>();const motifs=new Map<string,number>();for(const p of content.posts.filter(x=>x.status==='published')){p.themes.forEach(x=>theme.set(x,(theme.get(x)??0)+1));const s=p.visualSignature??inferVisualSignature(`${p.visualConcept??''} ${p.imagePrompt??''}`);s.objects.forEach(x=>objects.set(x,(objects.get(x)??0)+1));compositions.set(s.composition,(compositions.get(s.composition)??0)+1);s.motifs.forEach(x=>motifs.set(x,(motifs.get(x)??0)+1));}for(const r of content.visualReferences){r.objects.forEach(x=>objects.set(x,(objects.get(x)??0)+1));compositions.set(r.composition,(compositions.get(r.composition)??0)+1);r.motifs.forEach(x=>motifs.set(x,(motifs.get(x)??0)+1));}const rank=(m:Map<string,number>)=>[...m.entries()].map(([name,count])=>({name,count})).sort((a,b)=>b.count-a.count);return {postCount:content.posts.filter(x=>x.status==='published').length,visualReferenceCount:content.visualReferences.length,themes:rank(theme),objects:rank(objects),compositions:rank(compositions),motifs:rank(motifs),recent:content.posts.filter(x=>x.status==='published').slice(0,12).map(p=>({id:p.id,title:p.title,publishedAt:p.publishedAt,themes:p.themes,visualSignature:p.visualSignature??inferVisualSignature(`${p.visualConcept??''} ${p.imagePrompt??''}`),visualReferenceId:p.visualReferenceId}))};}
export async function createPostDraft(input:{title:string;angle:string;themes?:string[]}){const content=await loadLinkedInContent();const themes=input.themes?.length?input.themes:inferThemes(`${input.title} ${input.angle}`);const body=`${input.title}\n\n${input.angle}\n\nEstrutura sugerida:\n1. Abra com uma tese clara — sem “o futuro de...”.\n2. Mostre a tensão ou trade-off real.\n3. Traga 2–3 implicações práticas para produto/mercado.\n4. Feche com uma pergunta específica que convide debate qualificado.`;const visualConcept=conceptFor(themes);const signature=inferVisualSignature(visualConcept);const used=visualCounts(content);const warnings=signature.objects.filter(o=>(used.get(o)??0)>0).map(o=>`${o} (${used.get(o)} usos)`);return addLinkedInPost({title:input.title,body,status:'draft',themes,visualConcept,visualSignature:signature,imagePrompt:imagePromptFor(input.title,visualConcept,content.visualProfile,warnings),notes:warnings.length?`Visual history warning: ${warnings.join(', ')}`:'Draft criado pelo LinkedIn Content Intelligence; refinar texto antes de publicar.'});}
