import { readFile } from 'node:fs/promises';
import { runtimePath } from './config.js';
import { writeJsonAtomic } from './storage.js';

export type TrustedSourceId='bcb'|'cvm'|'bis'|'fsb'|'febraban';
export type TrustedSource={id:TrustedSourceId;name:string;url:string;feedUrl?:string;authority:'national-regulator'|'international-standard-setter'|'industry-association';weight:number};
export type TrustedSignal={id:string;sourceId:TrustedSourceId;sourceName:string;title:string;url:string;publishedAt?:string;summary?:string;relevance:number;themes:string[];fetchedAt:string;freshnessDays?:number;dateVerified:boolean};
export type SourceFetchStatus={sourceId:TrustedSourceId;ok:boolean;count:number;error?:string;fetchedAt:string};
export type TrustedSourceSnapshot={signals:TrustedSignal[];sources:TrustedSource[];status:SourceFetchStatus[];fetchedAt:string;expiresAt:string};

const cacheFile=()=>runtimePath('trusted-source-radar.json');
const CACHE_MS=30*60*1000;
const DAY_MS=24*60*60*1000;
export const MAX_TRUSTED_SIGNAL_AGE_DAYS=60;

export const TRUSTED_SOURCES:TrustedSource[]=[
  {id:'bcb',name:'Banco Central do Brasil',url:'https://www.bcb.gov.br/noticias',authority:'national-regulator',weight:1.25},
  {id:'cvm',name:'Comissão de Valores Mobiliários',url:'https://www.gov.br/cvm/pt-br/assuntos/noticias',authority:'national-regulator',weight:1.2},
  {id:'bis',name:'Bank for International Settlements',url:'https://www.bis.org/',feedUrl:'https://www.bis.org/doclist/all_pressrels.rss',authority:'international-standard-setter',weight:1.05},
  {id:'fsb',name:'Financial Stability Board',url:'https://www.fsb.org/',feedUrl:'https://www.fsb.org/wordpress/content_type/press-releases/feed/',authority:'international-standard-setter',weight:1.1},
  {id:'febraban',name:'FEBRABAN',url:'https://portal.febraban.org.br/noticias',authority:'industry-association',weight:1.05},
];
const TOPICS:{theme:string;keys:string[];weight:number}[]=[
  {theme:'Stablecoins',keys:['stablecoin','stablecoins'],weight:6},{theme:'Digital Assets',keys:['digital asset','ativos digitais','crypto','cripto','tokeniza','tokenisation','tokenization'],weight:5},{theme:'Drex',keys:['drex','real digital'],weight:6},{theme:'Open Finance',keys:['open finance','open banking'],weight:5},{theme:'Pagamentos',keys:['payment','payments','pagamento','pagamentos','pix','cross-border'],weight:4},{theme:'IA',keys:['artificial intelligence','inteligência artificial','inteligencia artificial',' ai ',' ia '],weight:5},{theme:'Infraestrutura Financeira',keys:['financial infrastructure','infraestrutura financeira','settlement','liquidação','liquidacao','clearing','resilience','resiliência'],weight:3},{theme:'Regulação',keys:['regulation','regulatory','supervision','supervisory','regulação','regulacao','norma','resolução','resolucao','consulta pública','consultation'],weight:3},{theme:'Identidade Digital',keys:['digital identity','identidade digital'],weight:4},
];
function decode(v:string){return v.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();}
function score(title:string,summary=''){const text=` ${decode(`${title} ${summary}`).toLowerCase()} `;let points=0;const themes:string[]=[];for(const topic of TOPICS){if(topic.keys.some(k=>text.includes(k))){points+=topic.weight;themes.push(topic.theme);}}if(/press release|notícia|noticias|news|report|relatório|relatorio|consulta|consultation|regulat|supervis/.test(text))points+=1;return {relevance:Math.min(100,Math.round(points*12)),themes:[...new Set(themes)]};}
function absolute(base:string,href:string){try{const resolved=new URL(href,base).toString();if(/portal\.febraban\.org\.br/i.test(base)&&!/febraban\.org\.br/i.test(resolved))return base;return resolved;}catch{return base;}}
function safeDate(value?:string){if(!value)return undefined;let normalized=value.trim();const br=normalized.match(/^(\d{1,2})\/(\d{1,2})\/(20\d{2})$/);if(br)normalized=`${br[3]}-${br[2].padStart(2,'0')}-${br[1].padStart(2,'0')}T12:00:00Z`;const d=new Date(normalized);return Number.isNaN(d.getTime())?undefined:d.toISOString();}
export function trustedSignalFreshness(publishedAt?:string,now=Date.now()){if(!publishedAt)return {dateVerified:false as const};const ms=Date.parse(publishedAt);if(!Number.isFinite(ms))return {dateVerified:false as const};return {dateVerified:true as const,freshnessDays:Math.max(0,Math.floor((now-ms)/DAY_MS))};}
export function isTrustedSignalFresh(signal:Pick<TrustedSignal,'publishedAt'|'dateVerified'|'freshnessDays'>,maxDays=MAX_TRUSTED_SIGNAL_AGE_DAYS){const freshness=signal.dateVerified&&typeof signal.freshnessDays==='number'?signal:trustedSignalFreshness(signal.publishedAt);return freshness.dateVerified&&typeof freshness.freshnessDays==='number'&&freshness.freshnessDays<=maxDays;}
function xmlTag(block:string,tag:string){const m=block.match(new RegExp(`<${tag}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${tag}>`,'i'));return m?decode(m[1]):'';}
function parseRss(source:TrustedSource,xml:string):TrustedSignal[]{const blocks=[...xml.matchAll(/<item\b[\s\S]*?<\/item>/gi)].map(x=>x[0]).concat([...xml.matchAll(/<entry\b[\s\S]*?<\/entry>/gi)].map(x=>x[0]));const now=new Date().toISOString();const out:TrustedSignal[]=[];for(const block of blocks.slice(0,40)){const title=xmlTag(block,'title');if(!title)continue;const link=xmlTag(block,'link')||block.match(/<link[^>]+href=["']([^"']+)/i)?.[1]||source.url;const summary=xmlTag(block,'description')||xmlTag(block,'summary')||xmlTag(block,'content');const publishedAt=safeDate(xmlTag(block,'pubDate')||xmlTag(block,'published')||xmlTag(block,'updated'));const s=score(title,summary);const f=trustedSignalFreshness(publishedAt);if(s.relevance<12||!f.dateVerified)continue;const signal:TrustedSignal={id:`${source.id}:${Buffer.from(`${title}|${link}`).toString('base64url').slice(0,22)}`,sourceId:source.id,sourceName:source.name,title,url:absolute(source.url,link),publishedAt,summary:summary.slice(0,360),relevance:Math.min(100,Math.round(s.relevance*source.weight)),themes:s.themes,fetchedAt:now,...f};if(isTrustedSignalFresh(signal))out.push(signal);}return out;}
function parseHtml(source:TrustedSource,html:string):TrustedSignal[]{const now=new Date().toISOString();const out:TrustedSignal[]=[];const candidates=[...html.matchAll(/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)];for(const match of candidates.slice(0,600)){const title=decode(match[2]);if(title.length<18||title.length>240)continue;const href=absolute(source.url,match[1]);if(source.id==='bcb'&&!/bcb\.gov\.br/i.test(href))continue;if(source.id==='cvm'&&!/gov\.br\/cvm/i.test(href))continue;const s=score(title);if(s.relevance<12)continue;const nearby=html.slice(Math.max(0,match.index!-220),Math.min(html.length,match.index!+match[0].length+240));const rawDate=nearby.match(/(\d{1,2}\/\d{1,2}\/20\d{2}|20\d{2}-\d{2}-\d{2})/)?.[1];const publishedAt=safeDate(rawDate);const f=trustedSignalFreshness(publishedAt);if(!f.dateVerified)continue;const signal:TrustedSignal={id:`${source.id}:${Buffer.from(`${title}|${href}`).toString('base64url').slice(0,22)}`,sourceId:source.id,sourceName:source.name,title,url:href,publishedAt,relevance:Math.min(100,Math.round(s.relevance*source.weight)),themes:s.themes,fetchedAt:now,...f};if(isTrustedSignalFresh(signal))out.push(signal);if(out.length>=30)break;}return out;}
async function fetchSource(source:TrustedSource){const target=source.feedUrl??source.url;const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),9000);try{const response=await fetch(target,{headers:{'user-agent':'Munin/0.1 Trusted Source Radar','accept':'application/rss+xml, application/atom+xml, text/xml, text/html;q=0.9'},signal:controller.signal});if(!response.ok)throw new Error(`HTTP ${response.status}`);const text=await response.text();const signals=source.feedUrl?parseRss(source,text):parseHtml(source,text);return {signals,status:{sourceId:source.id,ok:true,count:signals.length,fetchedAt:new Date().toISOString()} satisfies SourceFetchStatus};}catch(error){return {signals:[] as TrustedSignal[],status:{sourceId:source.id,ok:false,count:0,error:error instanceof Error?error.message:String(error),fetchedAt:new Date().toISOString()} satisfies SourceFetchStatus};}finally{clearTimeout(timeout);}}
async function loadCache(){try{return JSON.parse(await readFile(cacheFile(),'utf8')) as TrustedSourceSnapshot;}catch{return undefined;}}
async function saveCache(snapshot:TrustedSourceSnapshot){await writeJsonAtomic(cacheFile(),snapshot);}
function sanitizeCached(snapshot:TrustedSourceSnapshot){const signals=(snapshot.signals??[]).map(signal=>({...signal,...trustedSignalFreshness(signal.publishedAt)})).filter(isTrustedSignalFresh);return {...snapshot,signals};}
function dedupe(signals:TrustedSignal[]){const seen=new Set<string>();return signals.filter(s=>{const key=s.url.toLowerCase();if(seen.has(key))return false;seen.add(key);return true;}).sort((a,b)=>(b.relevance-a.relevance)+(Number(a.freshnessDays??999)-Number(b.freshnessDays??999)));}
export async function refreshTrustedSourceRadar():Promise<TrustedSourceSnapshot>{const results=await Promise.all(TRUSTED_SOURCES.map(fetchSource));const fetchedAt=new Date().toISOString();const snapshot:TrustedSourceSnapshot={signals:dedupe(results.flatMap(x=>x.signals)).slice(0,60),sources:TRUSTED_SOURCES,status:results.map(x=>x.status),fetchedAt,expiresAt:new Date(Date.now()+CACHE_MS).toISOString()};await saveCache(snapshot);return snapshot;}
export async function trustedSourceRadar(force=false):Promise<TrustedSourceSnapshot>{const raw=await loadCache();const cached=raw?sanitizeCached(raw):undefined;if(!force&&cached&&Date.parse(cached.expiresAt)>Date.now())return cached;const fresh=await refreshTrustedSourceRadar();if(!fresh.signals.length&&cached?.signals?.length)return {...cached,status:fresh.status,fetchedAt:fresh.fetchedAt,expiresAt:new Date(Date.now()+10*60*1000).toISOString()};return fresh;}
export function topSignalsForThemes(snapshot:TrustedSourceSnapshot,themes:string[],limit=5){const wanted=new Set(themes.map(x=>x.toLowerCase()));return snapshot.signals.filter(isTrustedSignalFresh).map(s=>({...s,themeMatches:s.themes.filter(t=>wanted.has(t.toLowerCase())).length})).filter(s=>s.themeMatches>0||s.relevance>=60).sort((a,b)=>(b.themeMatches-a.themeMatches)*30+(b.relevance-a.relevance)+(Number(a.freshnessDays??999)-Number(b.freshnessDays??999))).slice(0,limit);}
