import { readFile } from 'node:fs/promises';
import { runtimePath } from './config.js';
import { writeJsonAtomic } from './storage.js';
import { loadImageSettings } from './image-settings.js';
import { loadLinkedInContent, type VisualReference } from './linkedin-content.js';

export type VisualAnalysis={objects:string[];composition:string;palette:string[];materials:string[];motifs:string[];style:string[];lighting:string;background:string;textPresence:'none'|'minimal'|'prominent';peoplePresence:boolean;description:string;confidence:number;analyzedAt:string};
export type VisualAnalysisRecord={referenceId:string;analysis:VisualAnalysis;similar:{id:string;label:string;score:number}[];noveltyScore:number;model:string;updatedAt:string};
type VisualIntelligenceState={records:Record<string,VisualAnalysisRecord>;updatedAt:string};
const file=()=>runtimePath('visual-intelligence.json');
const empty=():VisualIntelligenceState=>({records:{},updatedAt:new Date(0).toISOString()});
async function loadState(){try{return {...empty(),...(JSON.parse(await readFile(file(),'utf8')) as VisualIntelligenceState)};}catch{return empty();}}
async function saveState(state:VisualIntelligenceState){state.updatedAt=new Date().toISOString();await writeJsonAtomic(file(),state);return state;}
function safeBase(url:string){return url.replace(/\/$/,'');}
function uniq(values:unknown){return Array.isArray(values)?[...new Set(values.filter((x):x is string=>typeof x==='string').map(x=>x.trim()).filter(Boolean))].slice(0,12):[];}
function text(value:unknown,fallback=''){return typeof value==='string'&&value.trim()?value.trim():fallback;}
function number(value:unknown,fallback=0){const n=typeof value==='number'?value:Number(value);return Number.isFinite(n)?Math.max(0,Math.min(100,n)):fallback;}
function responseText(payload:any){if(typeof payload?.output_text==='string')return payload.output_text;for(const item of payload?.output??[]){for(const part of item?.content??[]){if(typeof part?.text==='string')return part.text;}}return '';}
function parseJson(raw:string){const cleaned=raw.trim().replace(/^```json\s*/i,'').replace(/^```/,'').replace(/```$/,'').trim();const start=cleaned.indexOf('{'),end=cleaned.lastIndexOf('}');if(start<0||end<start)throw new Error('O modelo não retornou JSON válido.');return JSON.parse(cleaned.slice(start,end+1)) as Record<string,unknown>;}
function normalizeAnalysis(raw:Record<string,unknown>):VisualAnalysis{const presence=text(raw.textPresence,'none');return {objects:uniq(raw.objects),composition:text(raw.composition,'editorial minimalista'),palette:uniq(raw.palette),materials:uniq(raw.materials),motifs:uniq(raw.motifs),style:uniq(raw.style),lighting:text(raw.lighting),background:text(raw.background),textPresence:presence==='prominent'?'prominent':presence==='minimal'?'minimal':'none',peoplePresence:Boolean(raw.peoplePresence),description:text(raw.description),confidence:number(raw.confidence,75),analyzedAt:new Date().toISOString()};}
function similarity(a:VisualAnalysis,b:VisualAnalysis){const setA=new Set([...a.objects,...a.palette,...a.materials,...a.motifs,...a.style,a.composition].map(x=>x.toLowerCase()));const setB=new Set([...b.objects,...b.palette,...b.materials,...b.motifs,...b.style,b.composition].map(x=>x.toLowerCase()));const union=new Set([...setA,...setB]);if(!union.size)return 0;let intersection=0;for(const x of setA)if(setB.has(x))intersection++;return Math.round(intersection/union.size*100);}
export async function visualIntelligenceStatus(){const s=await loadImageSettings();const state=await loadState();return {enabled:Boolean(s.enabled&&s.apiKey&&s.baseUrl),model:s.visionModel??'gpt-5-mini',provider:'openai-responses',analyzed:Object.keys(state.records).length};}
export async function visualIntelligenceRecords(){return (await loadState()).records;}
export async function analyzeVisualReference(id:string){const content=await loadLinkedInContent();const ref=content.visualReferences.find(x=>x.id===id);if(!ref?.sourcePath||!ref.mimeType)throw new Error('A referência não possui imagem local.');const settings=await loadImageSettings();if(!settings.enabled||!settings.apiKey)throw new Error('Configure a OpenAI API em Image AI antes de usar Visual Intelligence.');const bytes=await readFile(ref.sourcePath);const dataUrl=`data:${ref.mimeType};base64,${bytes.toString('base64')}`;const model=settings.visionModel??'gpt-5-mini';const prompt='Analyze this LinkedIn editorial image as a visual art director. Return ONLY valid JSON with keys: objects (array of central objects/symbols), composition (short string), palette (array of dominant color families), materials (array), motifs (array of visual effects/recurring motifs), style (array of style labels), lighting (short string), background (short string), textPresence (one of none/minimal/prominent), peoplePresence (boolean), description (one concise sentence), confidence (0-100). Focus on reusable visual-signature metadata, not image quality.';
const r=await fetch(`${safeBase(settings.baseUrl)}/responses`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${settings.apiKey}`},body:JSON.stringify({model,input:[{role:'user',content:[{type:'input_text',text:prompt},{type:'input_image',image_url:dataUrl,detail:'auto'}]}]})});
if(!r.ok){const detail=await r.text();throw new Error(`Falha na análise visual (${r.status}): ${detail.slice(0,300)}`);}const payload=await r.json();const analysis=normalizeAnalysis(parseJson(responseText(payload)));const state=await loadState();const peers=content.visualReferences.filter(x=>x.id!==id&&state.records[x.id]).map(x=>({id:x.id,label:x.label,score:similarity(analysis,state.records[x.id].analysis)})).sort((a,b)=>b.score-a.score).slice(0,5);const noveltyScore=Math.max(0,100-(peers[0]?.score??0));const record:VisualAnalysisRecord={referenceId:id,analysis,similar:peers,noveltyScore,model,updatedAt:new Date().toISOString()};state.records[id]=record;await saveState(state);return {reference:ref,...record};}
export async function analyzeAllVisualReferences(limit=20){const content=await loadLinkedInContent();const state=await loadState();const pending=content.visualReferences.filter(x=>x.sourcePath&&!state.records[x.id]).slice(0,Math.max(1,Math.min(limit,50)));const results:{id:string;ok:boolean;error?:string}[]=[];for(const ref of pending){try{await analyzeVisualReference(ref.id);results.push({id:ref.id,ok:true});}catch(error){results.push({id:ref.id,ok:false,error:error instanceof Error?error.message:String(error)});}}return {processed:results.length,success:results.filter(x=>x.ok).length,failed:results.filter(x=>!x.ok).length,results};}
export async function visualSimilarityTo(reference:VisualReference,others:VisualReference[]){const state=await loadState();const source=state.records[reference.id];if(!source)return[];return others.filter(x=>x.id!==reference.id&&state.records[x.id]).map(x=>({id:x.id,label:x.label,score:similarity(source.analysis,state.records[x.id].analysis)})).sort((a,b)=>b.score-a.score).slice(0,5);}
